'use strict';
const $=s=>document.querySelector(s);let snapshot=null,selected='',lastRender='',toastTimer,outputInitialized=false;
const statuses={SENDING:'发送中',QUEUED:'节点已接收',WAITING_CLOCK:'等待局内时间',TRACKING_UNRESOLVED:'道具关联待确认',TRACKING_UNAVAILABLE:'道具追踪未接入',DETECTED:'等待规划',SCHEDULED:'暂定计划',COMMITTED:'已锁定',CAPTURING:'录制中',STOPPING:'结束录制',FINALIZING:'素材处理',TRANSFERRING:'回传中',READY:'素材就绪',FAILED:'失败',CANCELLED:'旧会话',CONFLICT:'视角冲突',MISSED_WINDOW:'错过窗口',UNCERTAIN:'待核验',IDENTITY_UNKNOWN:'身份未确认',PIN_CONFLICT:'手动指定冲突'};
function escapeHTML(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className='toast'+(error?' error':'');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.add('hidden'),6000)}
async function api(path,data){const r=await fetch('/api/'+path,{method:data===undefined?'GET':'POST',headers:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const body=await r.json();if(!r.ok){throw Error(body.error||`请求失败 ${r.status}`)}return body}
async function action(fn){try{await fn();await refresh()}catch(e){toast(e.message,true)}}
function time(ms){return new Date(ms).toLocaleTimeString('zh-CN',{hour12:false})}
function render(s){$('.version').textContent=s.version;snapshot=s;const state=s.state,c=state.config;for(const key of ['events','jobs','artifacts','queue','half_queue','full_queue','logs'])state[key]??=[];
 $('#hud-zip-import').disabled=s.hud_import?.phase==='starting';$('#hud-zip-file').disabled=s.hud_import?.phase==='starting';$('#hud-import-status').textContent=s.hud_import?.message||(s.state.hud_package?.name?'已导入：'+s.state.hud_package.name:'ZIP 最大 100 MB，导入后自动启用');$('#obs-start').disabled=s.obs_launch?.phase==='starting';$('#obs-launch-status').textContent=s.obs_launch?.message||'';$('#hud-obs').disabled=s.obs_launch?.phase==='starting';$('#page-title').textContent=s.role==='agent'?'Linux 录制台':'回放导播台';$('#hud-controls').classList.toggle('hidden',s.role!=='agent');$('#hud-source-status').textContent=s.state.hud_active_source?'当前 HUD 源：'+s.state.hud_active_source:'';for(const id of ['hud-show','hud-hide'])$('#'+id).disabled=c.mode!=='live'||state.jobs.some(j=>['COMMITTED','CAPTURING','STOPPING'].includes(j.status));
 $('#hud-show').disabled ||= !!state.hud_active_source;
 $('#mode-badge').textContent=c.mode==='demo'?'演示模式':'实时工作流';$('#match').textContent=c.match;$('#map').textContent=`${c.map||"等待 GSI 识别地图"} / E${c.epoch}`;const clock=s.round_clocks?.[s.role==='agent'?'b':'a']?.clock;$('#delta').textContent=clock?`R${clock.round} · ${clock.phase} ${clock.remaining.toFixed(1)}s`:'等待 GSI 倒计时';
 $('#node').textContent=c.connection_mode==='relay'?(s.relay?.peer?'中继 · '+s.relay.peer:'中继 · 等待配对'):s.role==='agent'?'本机 Linux Agent':(c.worker_url?'远程 Linux 节点':'本机演示 / 录制');$('#count').innerHTML=`${state.artifacts.length} <small>CLIPS</small>`;$('#pause-btn').textContent=c.paused?'启用采集':'暂停采集';$('#connection').innerHTML='<i></i> 本地服务在线';$('#footer-status').textContent=`${s.role.toUpperCase()} · ${c.paused?'采集暂停':'采集已启用'} · EPOCH ${c.epoch}`;
 $('#notice').textContent=s.storage_error?`存储错误：${s.storage_error}`:c.mode==='demo'?'演示模式使用测试画面，不会控制游戏或 OBS。点击「演示一轮」查看冲突选择与1.5 秒出片。':'自动击杀按回合 + 阶段倒计时发送和录制，无需 tick 或手工校准。连续击杀合并录制；同人连杀优先，异地击杀直接切镜。保枪击杀计入原回合。';
 $('#demo-btn').classList.toggle('hidden',!c.test_mode);$('#demo-btn').disabled=c.mode!=='demo';$('#program-state').textContent=s.output?.id?(s.output.due?'等待自动播出':'回放播出中'):(s.output_online?'输出已连接 · 透明': 'OBS 输出未连接');$('#return-btn').disabled=!s.output?.id;renderOutputSettings(s);renderLocalDemo(s);renderTeams(s);renderRelay(s);
 const renderKey=JSON.stringify([state.events,state.artifacts,state.queue,state.half_queue,state.full_queue,state.output.half_manual,$('#round-select').value,$('#event-filter').value,$('#search').value,selected]);if(renderKey!==lastRender){lastRender=renderKey;renderEvents(state.events);renderLibrary(state.artifacts);renderRoundOptions(state);renderQueue(state.queue,state.artifacts);renderHalfQueue(state.half_queue,state.artifacts);renderFullQueue(state.full_queue,state.artifacts)}
 $('#event-count').textContent=state.events.length;$('#queue-count').textContent=state.queue.length;$('#library-count').textContent=state.artifacts.length;
 $('#logs').innerHTML=[...state.logs].reverse().map(l=>`<div class="log-row ${l.level==='warn'?'warn':''}"><time>${time(l.time)}</time><span>${escapeHTML(l.message)}</span></div>`).join('');
}
function renderEvents(events){const filter=$('#event-filter').value;const list=events.filter(e=>filter==='all'||e.status===filter).slice().reverse();if(!list.length){$('#events').innerHTML='<div class="empty"><span>⌁</span><h3>等待第一条击杀</h3><p>接入 GSI 或手动添加事件<br>算法会自动比较可录制窗口</p></div>';return}
 $('#events').innerHTML=list.map(e=>`<article class="event ${e.status==='SCHEDULED'?'scheduled':e.status==='READY'?'ready':''}"><div class="event-top"><div class="event-player"><div class="avatar">${escapeHTML((e.name||e.player).slice(0,2).toUpperCase())}</div><div><div class="event-name">${escapeHTML(e.name||e.player)}</div><span class="event-timing">R${e.round} · ${e.clock?escapeHTML(e.clock.phase)+' · 剩余 '+e.clock.remaining.toFixed(1)+'s':e.round_timing?'缺少倒计时':time(e.time)}</span></div></div><button class="pin ${e.pin?'on':''}" data-pin="${escapeHTML(e.id)}" ${e.job_id?'disabled':''}>${e.pin?'已指定':'指定'}</button></div><div class="event-line"><span class="status ${['READY','SCHEDULED','CAPTURING'].includes(e.status)?'good':['FAILED','CONFLICT','MISSED_WINDOW','PIN_CONFLICT'].includes(e.status)?'bad':''}">${statuses[e.status]||e.status}</span><span class="badge">${e.quality==='demo'?'演示':e.quality==='verified'?'事件已核验':'推断'} · ${e.round_timing?'回合时钟':e.tick??'时间估计'}</span></div><p class="event-reason">${e.utility?'道具追踪 · '+escapeHTML(e.utility.kind)+' · '+escapeHTML(e.utility.id||'实例待确认')+'<br>':''}${escapeHTML(e.reason)}</p></article>`).join('')}
function renderLibrary(arts){const term=$('#search').value.toLowerCase();const list=arts.filter(a=>(a.name+' '+a.player+' '+a.round).toLowerCase().includes(term));$('#library').innerHTML=list.length?list.slice().reverse().map(a=>`<button class="clip ${selected===a.id?'selected':''}" data-select="${a.id}"><div class="clip-art">▷<span class="badge">${a.duration.toFixed(2)}s</span></div><div class="clip-text"><strong>${escapeHTML(a.name||a.player)}</strong><p>ROUND ${String(a.round).padStart(2,'0')} · ${a.demo?'演示素材':'近似定位'}</p></div></button>`).join(''):'<div class="empty compact"><p>暂无匹配素材；录制完成后将显示在这里</p></div>';}
function currentArts(){const s=snapshot.state,c=s.config;return s.artifacts.filter(a=>s.jobs.some(j=>j.id===a.job_id&&j.match===c.match&&j.map===c.map&&j.epoch===c.epoch))}
function renderRoundOptions(state){const select=$('#round-select'),value=select.value;const rounds=[...new Set([...currentArts().map(a=>a.round),...currentEvents().map(e=>e.round)])].sort((a,b)=>a-b);select.innerHTML=rounds.map(r=>`<option value="${r}">第 ${r} 回合</option>`).join('');if(rounds.includes(Number(value)))select.value=value;else if(rounds.length)select.value=rounds[rounds.length-1];}
function queueRows(ids,arts,kind){return ids.map((id,i)=>{const a=arts.find(x=>x.id===id);return a?`<div class="queue-item"><span class="queue-num">${i+1}</span><div class="queue-info" data-select="${id}" tabindex="0" role="button"><strong>${escapeHTML(a.name)}</strong><p>R${a.round} · ${a.duration.toFixed(2)}s</p></div><div class="queue-buttons" ${kind==='half'&&!snapshot.state.output.half_manual?'hidden':''}><button data-order="${id}" data-kind="${kind}" data-step="-1" ${i===0?'disabled':''}>↑</button><button data-order="${id}" data-kind="${kind}" data-step="1" ${i===ids.length-1?'disabled':''}>↓</button><button data-delete="${id}" data-kind="${kind}" title="从列表移除">✕</button>${kind==='round'?`<button data-half="${id}" title="选入半场精选">${snapshot.state.half_queue.includes(id)?'★':'☆'}</button>`:''}</div></div>`:''}).join('')||'<p class="empty compact">列表为空</p>'}
function roundIDs(){const r=Number($('#round-select').value),allowed=new Set(currentArts().filter(a=>a.round===r).map(a=>a.id));return snapshot.state.queue.filter(id=>allowed.has(id))}
function currentEvents(){const s=snapshot.state,c=s.config;return s.events.filter(e=>e.epoch===c.epoch&&e.match===c.match&&e.map===c.map)}
function renderQueue(ids,arts){const round=Number($('#round-select').value);const pending=currentEvents().filter(e=>e.round===round&&!currentArts().some(a=>a.event_id===e.id));$('#queue').innerHTML=queueRows(roundIDs(),arts,'round')+pending.map(e=>`<div class="queue-item pending"><span class="queue-num">…</span><div class="queue-info"><strong>${escapeHTML(e.name||e.player)}</strong><p>${escapeHTML(statuses[e.status]||e.status)} · 就绪后追加到末尾</p></div></div>`).join('')}

function renderHalfQueue(ids,arts){$('#half-mode').textContent=snapshot.state.output.half_manual?'手动精选 · 可排序和移除':'自动收集上半场 · 按回合及击杀发生时间排序';$('#half-count').textContent=ids.length;$('#half-queue').innerHTML=queueRows(ids,arts,'half')}
function renderFullQueue(ids,arts){$('#full-count').textContent=ids.length;$('#full-queue').innerHTML=queueRows(ids,arts,'full')}
function renderOutputSettings(s){const o=s.state.output;$('#output-url').value=location.origin+s.output_url;$('#hotkey-status').textContent=s.hotkey_status+(s.output_error?' · '+s.output_error:'');for(const n of [1,2])$('#transition'+n+'-status').textContent=o['transition'+n]?'已导入':'未导入（跳过）';$('#half-btn').disabled=!selected||!o.half_manual;if(!outputInitialized){$('#auto-half-collect').checked=!o.half_manual;$('#auto-full-collect').checked=!o.full_manual;$('#auto-round').checked=o.auto_round;$('#auto-half').checked=o.auto_half;$('#auto-full').checked=o.auto_full;$('#half-round').value=o.half_round;$('#output-delay').value=o.delay;$('#output-hotkey').value=o.hotkey;outputInitialized=true}}
async function addHalf(id){if(!snapshot.state.output.half_manual){toast('R1–R12 击杀就绪后自动加入半场精选');return;}const ids=[...snapshot.state.half_queue];if(!ids.includes(id))ids.push(id);await api('output/queue',{kind:'half',ids});toast('已选入半场精选')}
function selectClip(id){const a=snapshot.state.artifacts.find(v=>v.id===id);if(!a)return;selected=id;$('#preview').src='/api/media/'+id;$('#preview').classList.remove('hidden');$('#preview-empty').classList.add('hidden');$('#clip-name').textContent=a.name||a.player;$('#clip-meta').textContent=`R${a.round} · ${a.duration.toFixed(2)} 秒 · ${(a.size/1048576).toFixed(2)} MB · ${a.demo?'演示素材':'近似时间'}${a.utility?' · 道具追踪 '+a.utility.kind:''}`;$('#preview-subtitle').textContent=a.demo?'测试图与测试音频 · 仅用于流程验证':'SHA-256 校验通过 · 请确认击杀位置与视角';$('#queue-btn').disabled=false;$('#play-btn').disabled=false;$('#half-btn').disabled=false;render(snapshot)}
async function refresh(){try{render(await api('state'))}catch(e){$('#connection').textContent='服务未连接';if(!snapshot)toast(e.message,true)}}
const fields=[['connection_mode','连接方式','select',['lan','relay']],['relay_url','云服务器 IP（默认 7790；可填 IP:端口或 HTTPS 地址）'],['relay_group','群组码（4 位数字，例如 0001）'],['relay_name','中继设备名称'],['relay_auto_pair','开启自动配对（仅录制机生效）','checkbox'],['test_mode','测试模式（显示 Demo 联调）','checkbox'],['auto_send_gotv','保存配置时自动将 GOTV2 发至 Linux 并连接','checkbox'],['mode','运行模式','select',['demo','live']],['match','比赛名称'],['worker_url','Linux 节点 URL（导播端）'],['obs_url','本机 OBS WebSocket'],['obs_password','OBS 密码（留空保留）','password'],['event_source','击杀事件来源','select',['gsi','parser']],['tracking_mode','道具追踪后端','select',['bridge','native']],['tracking_url','道具镜头适配器 URL'],['netcon','本机 CS2 NetCon 地址（A / B）'],['gotv','GOTV2 / B 路地址或平台指令：connect IP:端口;password xxx'],['gotv_password','GOTV 密码（指令自动提取；留空保留同一地址的密码）','password'],['session_lock','CSStudio session.lock 绝对路径'],['ffmpeg','FFmpeg 路径'],['ffprobe','FFprobe 路径'],['replay_scene','Windows OBS 回放场景'],['replay_input','Windows OBS 媒体源'],['guard','采集保护量（秒）','number'],['setup','设备启动提前量（秒，无预热）','number'],['transition','额外切换间隔（秒，默认 0）','number'],['strict','严格定位模式（当前将阻止实时出片）','checkbox'],['mappings','B 路已确认命令槽位映射（JSON）','textarea']];
function openSettings(){if(!snapshot)return;const c=snapshot.state.config;$('#config-fields').innerHTML=fields.map(([key,label,type='text',options])=>`<label class="${type==='checkbox'?'check-label':''}">${type==='checkbox'?'':escapeHTML(label)}${type==='select'?`<select name="${key}">${options.map(o=>`<option value="${o}" ${(c[key]|| (key==='connection_mode'?'lan':''))===o?'selected':''}>${o==='lan'?'局域网直连（原方案）':o==='relay'?'云中继':o==='demo'?'演示（不控制游戏）':o==='live'?'真实采集 / OBS 输出':o}</option>`).join('')}</select>`:type==='textarea'?`<textarea name="${key}" rows="3">${escapeHTML(JSON.stringify(c[key],null,2))}</textarea>`:`<input name="${key}" type="${type}" ${type==='checkbox'?(c[key]?'checked':''):`value="${escapeHTML(key==='epoch'?c.epoch+1:c[key]??'')}"`} ${key==='relay_group'?'inputmode="numeric" maxlength="4"':''} ${type==='number'?'step="0.05" min="0"':''}>`}${type==='checkbox'?escapeHTML(label):''}</label>`).join('');$('#cal-delta').value=c.delta;$('#cal-error').value=c.uncertainty;$('#epoch-info').textContent=`本地会话版本 ${c.epoch}；节点版本自动识别`;$('#settings').showModal()}
$('#settings-form').onsubmit=e=>{e.preventDefault();action(async()=>{const c={...snapshot.state.config};const f=e.target;for(const [key,,type] of fields){const input=f.elements[key];c[key]=type==='checkbox'?input.checked:type==='number'?Number(input.value):type==='textarea'?JSON.parse(input.value):input.value}await api('config',c);$('#settings').close();toast('配置已保存；按回合与局内时间自动发送')})};
$('#settings-btn').onclick=openSettings;$('#rail-settings').onclick=openSettings;
$('#pause-btn').onclick=()=>action(async()=>{await api('pause',{paused:!snapshot.state.config.paused})});
$('#demo-btn').onclick=()=>action(async()=>{await api('demo',{});toast('已注入一组冲突事件，预计约 12 秒后出片')});
$('#add-event').onclick=()=>$('#event-dialog').showModal();
$('#event-form').onsubmit=e=>{e.preventDefault();action(async()=>{const f=new FormData(e.target);await api('events',{utility:f.get('utility_kind')?{kind:f.get('utility_kind'),id:f.get('utility_id').trim(),evidence:f.get('utility_evidence').trim()}:undefined,name:f.get('name'),player:f.get('player'),time:snapshot.now+Number(f.get('delay'))*1000,round:Number(f.get('round')),kills:Number(f.get('kills')),quality:'inferred',uncertainty:snapshot.state.config.uncertainty,group_count:1});$('#event-dialog').close();toast('击杀候选已添加')})};
$('#calibrate-btn').onclick=()=>action(async()=>{await api('calibrate',{delta:Number($('#cal-delta').value),uncertainty:Number($('#cal-error').value)});toast('已应用实测校准，有效期 10 分钟')});
$('#remote-sync').onclick=()=>action(async()=>{await api('remote-sync',{});toast('节点时钟同步完成')});
$('#gotv-connect').onclick=()=>action(async()=>{const f=$('#settings-form');const p={gotv:f.elements.gotv.value.trim()};if(f.elements.gotv_password.value)p.password=f.elements.gotv_password.value;await api('connect-gotv',p);f.elements.gotv_password.value='';toast('已发送至 Linux：先设置密码再连接，请核验游戏画面')});
$('#health-btn').onclick=()=>action(async()=>{$('#health-result').textContent='正在探测 FFmpeg 和 OBS…';$('#health').showModal();$('#health-result').textContent=JSON.stringify(await api('preflight',{}),null,2)});
$('#queue-btn').onclick=()=>action(async()=>{if(!selected)return;const ids=[...snapshot.state.queue];if(!ids.includes(selected))ids.push(selected);await api('output/queue',{kind:'round',ids});toast('已加入本回合列表')});
$('#play-btn').onclick=()=>action(async()=>{const clip=snapshot.state.artifacts.find(a=>a.id===selected);await api('output/play',{kind:'round',round:clip.round});toast('已触发本回合网页输出')});
$('#return-btn').onclick=()=>action(async()=>{await api('output/stop',{})});
$('#logs-toggle').onclick=()=>{$('#logs').classList.toggle('expanded');$('#logs-toggle').textContent=$('#logs').classList.contains('expanded')?'收起日志':'展开日志'};
$('#event-filter').onchange=()=>render(snapshot);$('#search').oninput=()=>render(snapshot);
document.addEventListener('click',e=>{const b=e.target.closest('button,a,[data-select]');if(!b)return;if(b.dataset.close){$('#'+b.dataset.close).close();return}if(b.dataset.select){selectClip(b.dataset.select);return}if(b.dataset.pin)action(async()=>{const event=snapshot.state.events.find(x=>x.id===b.dataset.pin);await api('pin',{id:event.id,pin:!event.pin})});if(b.dataset.remove)action(async()=>{await api('queue',{ids:snapshot.state.queue.filter(x=>x!==b.dataset.remove)})});if(b.dataset.up)action(async()=>{const ids=[...snapshot.state.queue],i=ids.indexOf(b.dataset.up);if(i>0){[ids[i-1],ids[i]]=[ids[i],ids[i-1]];await api('queue',{ids})}})});
document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select')||document.querySelector('dialog[open]'))return;if(e.code==='Space'&&selected){e.preventDefault();const v=$('#preview');v.paused?v.play().catch(x=>toast(x.message,true)):v.pause()}if(e.key==='Escape'&&snapshot?.output?.id)$('#return-btn').click();if(e.key==='Enter'&&e.target.dataset.select)selectClip(e.target.dataset.select)});
refresh();setInterval(refresh,750);

$('#round-select').onchange=()=>render(snapshot);
$('#round-play').onclick=()=>action(()=>api('output/play',{kind:'round',round:Number($('#round-select').value)}));
$('#half-play').onclick=()=>action(()=>api('output/play',{kind:'half',round:0}));
$('#full-play').onclick=()=>action(()=>api('output/play',{kind:'full',round:0}));
$('#half-btn').onclick=()=>action(()=>addHalf(selected));
$('#save-output').onclick=()=>action(async()=>{await api('output/settings',{half_manual:!$('#auto-half-collect').checked,full_manual:!$('#auto-full-collect').checked,auto_round:$('#auto-round').checked,auto_half:$('#auto-half').checked,auto_full:$('#auto-full').checked,half_round:Number($('#half-round').value),delay:Number($('#output-delay').value),hotkey:$('#output-hotkey').value.trim()});toast('播出设置已保存')});
$('#copy-output').onclick=()=>action(async()=>{await navigator.clipboard.writeText($('#output-url').value);toast('已复制 OBS 浏览器源地址')});
for(const n of [1,2])$('#transition'+n).onchange=()=>action(async()=>{const input=$('#transition'+n),file=input.files[0];if(!file)return;input.disabled=true;try{const r=await fetch('/api/output/transition/'+n+'?name='+encodeURIComponent(file.name),{method:'POST',body:file});const result=await r.json();if(!r.ok)throw Error(result.error||'上传失败');toast('转场 '+n+' 已导入')}finally{input.disabled=false;input.value=''}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.half)action(()=>addHalf(b.dataset.half));if(b.dataset.order||b.dataset.delete)action(async()=>{const kind=b.dataset.kind,all=[...(kind==='full'?snapshot.state.full_queue:kind==='half'?snapshot.state.half_queue:snapshot.state.queue)],id=b.dataset.order||b.dataset.delete;let ids=all;if(b.dataset.delete)ids=all.filter(x=>x!==id);else{const visible=kind!=='round'?all:roundIDs(),i=visible.indexOf(id),other=visible[i+Number(b.dataset.step)];if(!other)return;const x=all.indexOf(id),y=all.indexOf(other);[all[x],all[y]]=[all[y],all[x]]}await api('output/queue',{kind,ids});if(kind==='full')$('#auto-full-collect').checked=false})});

for(const [id,visible] of [['hud-show',true],['hud-hide',false]])$('#'+id).onclick=()=>action(async()=>{await api('hud',{visible});toast(visible?'游戏已回读确认 HUD 开启':'游戏已回读确认 HUD 隐藏；录制时保持')});

const demoPhases={'':'未载入',loaded:'已发送载入命令，等待游戏完成载入',seeking:'已发送定位命令，等待检查就绪',ready:'已暂停在目标 tick，可以启动',armed:'等待定时开始',running:'已发送播放命令',stopped:'已停止',failed:'启动失败'};
function renderLocalDemo(s){$('#local-demo-panel').classList.toggle('hidden',!s.state.config.test_mode);$('#cs2-move-start').classList.toggle('hidden',s.role!=='agent');$('#cs2-move-start').disabled=s.cs2_launch?.phase==='starting';renderGSIStatus(s);$('#cs2-start').classList.toggle('hidden',s.role!=='agent');$('#cs2-start').disabled=s.cs2_launch?.phase==='starting';$('#cs2-launch-status').textContent=s.cs2_launch?.message||'';$('#cs2-close').classList.toggle('hidden',s.role!=='agent');const d=s.local_demo||{},phase=d.phase||'';const busy=['armed','running'].includes(phase),live=s.state.config.mode==='live';for(const id of ['demo-load','demo-seek','demo-ready'])$('#'+id).disabled=!live||busy;$('#demo-start').disabled=s.role!=='director'||phase!=='ready';$('#demo-stop-pair').disabled=s.role!=='director'||!d.run_id;$('#demo-stop').disabled=!phase;$('#demo-status').textContent=`${s.role==='agent'?'B / Linux':'A / Windows'} · ${demoPhases[phase]||phase}${d.path?' · '+d.path:''}${phase?' · tick '+d.tick:''}${phase==='armed'?' · '+Math.max(0,(d.due-s.now)/1000).toFixed(1)+' 秒后播放':''}${d.sent_at?' · 发送完成 '+time(d.sent_at):''}${d.error?' · '+d.error:''}`;}
for(const [id,operation] of [['demo-load','load'],['demo-seek','seek'],['demo-ready','ready'],['demo-start','start-pair'],['demo-stop','stop'],['demo-stop-pair','stop-pair']])$('#'+id).onclick=()=>action(async()=>{const b=$('#'+id);b.disabled=true;try{await api('local-demo',{action:operation,path:$('#demo-path').value.trim(),tick:Number($('#demo-tick').value),delay:Number($('#demo-delay').value)});toast(operation==='start-pair'?'双路已安排启动；等待 B 路 GSI 倒计时后自动录制':'Demo 操作完成，请查看状态和游戏画面')}finally{b.disabled=false}});

$('#cs2-close').onclick=()=>action(async()=>{const button=$('#cs2-close');button.disabled=true;try{const r=await api('cs2/close',{});toast(r.closed?'已彻底关闭 '+r.closed+' 个 CS2 进程，采集已暂停':'未发现运行中的 CS2；Demo 倒计时已取消，采集已暂停')}finally{button.disabled=false}});

$('#cs2-start').onclick=()=>action(async()=>{await api('cs2/start',{});toast('已开始无头启动，请查看启动状态')});

$('#cs2-move-start').onclick=()=>action(async()=>{await api('cs2/start',{move_steam:true});toast('正在退出桌面 Steam 并切换到无头显示器，请查看启动状态')});
function renderGSIStatus(s){$('#auto-capture').checked=!!s.state.config.auto_capture;const side=s.role==='agent'?'b':'a',d=s.gsi?.[side],c=s.state.config;let message=side.toUpperCase()+' 路 · ';if(!d?.received_at)message+='尚未收到 GSI，请确认配置已安装并重启 CS2';else if(d.error)message+=d.error;else if(s.now-d.accepted_at>5000)message+='GSI 已断流，最后接收 '+time(d.accepted_at);else if(side==='b')message+='在线 · 当前观战 '+(s.observed||'未知');else{message+='在线 · '+d.players+' 名选手 · '+d.counters+' 个击杀计数 · 已识别 '+d.detected+' 次变化';if(!d.counters)message+='；缺少 allplayers 击杀字段，请确认处于观战 / Demo 且安装 A 路配置';if(c.event_source==='parser')message+='；事件来源为 parser，GSI 自动击杀未启用';if(c.paused)message+='；采集已暂停';if(c.mode==='demo')message+='；演示模式不会发送真实击杀，请改为 live';if(!s.round_clocks?.a)message+='；缺少阶段倒计时，请安装最新 A 路 GSI 配置';if(c.connection_mode==='relay'&&!s.relay?.peer)message+='；云中继尚未配对';else if(c.connection_mode!=='relay'&&!c.worker_url)message+='；未配置 Linux 节点';}if(side==='a'&&s.gsi?.b?.error)message+='；'+s.gsi.b.error;const clock=s.round_clocks?.[side];if(clock&&(!clock.progress_at||s.now-clock.progress_at>1500))message+='；游戏倒计时未推进，请检查 Demo 播放状态';$('#gsi-status').textContent=message;}

$('#auto-capture').onchange=()=>action(async()=>{await api('auto-capture',{enabled:$('#auto-capture').checked});toast($('#auto-capture').checked?'已启用自动录制：校准有效后自动提交，不需逐条点击':'自动录制已关闭；已提交任务继续完成')});

let teamsInitialized=false,lastTeamManaged=null,teamLogos={ct:'',t:''};
function renderTeams(s){$('#teams-panel').classList.toggle('hidden',s.role!=='director');$('#cleanup').textContent=s.role==='director'?'一键清理两端 Replay 临时文件':'清理本机 Replay 临时文件';const teams=s.state.config.teams||{};if(lastTeamManaged!==!!teams.scoredeck_managed){lastTeamManaged=!!teams.scoredeck_managed;teamsInitialized=false;$('#teams-status').textContent=lastTeamManaged?'跟随 ScoreDeck 当前主赛':'独立队伍设置';}for(const side of ['ct','t'])for(const field of ['name','logo','clear'])$('#team-'+side+'-'+field).disabled=!!teams.scoredeck_managed;if(teams.scoredeck_managed)$('#teams-status').textContent='队名与队标跟随 ScoreDeck 当前主赛；开局阵营映射在外部设置中调整。';if(teamsInitialized&&!teams.scoredeck_managed)return;for(const side of ['ct','t']){$('#team-'+side+'-name').value=teams[side]?.name||'';teamLogos[side]=teams[side]?.logo||'';$('#team-'+side+'-status').textContent=teamLogos[side]?'已设置图标':'未设置图标';$('#team-'+side+'-preview').src=teamLogos[side];$('#team-'+side+'-preview').hidden=!teamLogos[side]}if(!teamsInitialized){$('#team-half').value=teams.half_rounds||12;$('#team-overtime').value=teams.overtime_half_rounds||3;}teamsInitialized=true;}
for(const side of ['ct','t']){$('#team-'+side+'-logo').onchange=()=>action(async()=>{const input=$('#team-'+side+'-logo'),file=input.files[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>1024*1024)throw Error('请选择不超过 1 MB 的 PNG / JPEG / WebP');teamLogos[side]=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('读取图标失败'));reader.readAsDataURL(file)});$('#team-'+side+'-status').textContent=file.name+'（待保存）';input.value=''});$('#team-'+side+'-clear').onclick=()=>{teamLogos[side]='';$('#team-'+side+'-status').textContent='已移除（待保存）'};}
$('#teams-save').onclick=()=>action(async()=>{const button=$('#teams-save');button.disabled=true;try{const result=await api('teams',{ct:{name:$('#team-ct-name').value.trim(),logo:teamLogos.ct},t:{name:$('#team-t-name').value.trim(),logo:teamLogos.t},half_rounds:Number($('#team-half').value),overtime_half_rounds:Number($('#team-overtime').value)});$('#teams-status').textContent=result.synced?'已保存并同步 Linux；在 Linux 点击“安装战队 HUD 到 OBS”即可录入视频':'已保存本机；请配置 Linux 节点后再次同步';toast($('#teams-status').textContent)}finally{button.disabled=false}});
async function applyHUD(){const r=await api('hud/obs',{});toast(r.warning||('HUD 已接入 OBS 场景：'+r.scene),!!r.warning);return r}
$('#hud-obs').onclick=()=>action(applyHUD);
$('#cleanup').onclick=()=>action(async()=>{if(!confirm('清除 Replay 两端的录制素材、事件、队列和缓存？配置、战队图标和当前转场会保留。'))return;const button=$('#cleanup');button.disabled=true;try{const r=await api('cleanup',{});selected='';lastRender='';$('#preview').pause();$('#preview').removeAttribute('src');$('#preview').load();$('#preview').classList.add('hidden');$('#preview-empty').classList.remove('hidden');for(const id of ['queue-btn','play-btn','half-btn'])$('#'+id).disabled=true;$('#clip-name').textContent='尚未选择素材';$('#clip-meta').textContent='每次击杀独立输出 · 固定1.5 秒';toast(r.remote_cleaned?'Windows 与 Linux 临时文件已清除，配置已保留':'本机临时文件已清除，配置已保留')}finally{button.disabled=false}});

$('#compact-timing').onclick=()=>action(async()=>{await api('timing/compact',{});toast('两端已启用紧凑间隔：准备 0.2 秒、额外间隔 0 秒；保护量按误差保留至少 0.2 秒')});

let relayViewKey="";
function renderRelay(s){
 const c=s.state.config,r=s.relay||{},enabled=c.connection_mode==='relay';
 const key=[enabled,c.relay_group,r.peer].join(':');if(key!==relayViewKey){$('#relay-nodes').textContent='';$('#relay-transfers').textContent='';relayViewKey=key}
 $('#relay-panel').classList.toggle('hidden',!enabled);
 $('#relay-status').textContent=r.error||(!r.online?'云中继连接中…':r.peer?'已配对 · '+r.peer+(r.peer_online?' · 对端在线':' · 对端离线，等待重连'):'已连接 · 等待同组设备');
 $('#relay-group-label').textContent='群组 '+(c.relay_group||'----')+' · '+(c.relay_name||c.relay_device||'');
 $('#relay-unpair').disabled=!r.peer;
 $('#relay-auto-label').classList.toggle('hidden',s.role!=='agent');
 if(document.activeElement!==$('#relay-auto'))$('#relay-auto').checked=!!c.relay_auto_pair;
 $('#relay-pending').classList.toggle('hidden',!r.pending||s.role!=='agent');
 $('#relay-pending-name').textContent=r.pending?'主机 '+r.pending+' 请求配对':'';
}
$('#relay-search').onclick=()=>action(async()=>{
 const group=snapshot.state.config.relay_group;const result=await api('relay/nodes');if(group!==snapshot.state.config.relay_group||snapshot.state.config.connection_mode!=='relay')return;
 $('#relay-nodes').innerHTML=result.nodes.length?result.nodes.map(n=>`<div class="queue-item"><div class="queue-info"><strong>${escapeHTML(n.name||n.id)}</strong><p>${escapeHTML(n.id)} · ${n.peer?'已有配对':n.auto?'自动配对已开启':'等待手动确认'}</p></div>${snapshot.role==='director'?`<button data-relay-pair="${escapeHTML(n.id)}" ${n.peer||result.self.peer?'disabled':''}>配对</button>`:''}</div>`).join(''):'<p>暂无在线的同组设备</p>';
});
$('#relay-nodes').onclick=e=>{const b=e.target.closest('[data-relay-pair]');if(b)action(async()=>{await api('relay/pair',{action:'request',target:b.dataset.relayPair});toast('配对请求已发送')})};
$('#relay-unpair').onclick=()=>action(async()=>{await api('relay/pair',{action:'unpair',target:''});$('#relay-nodes').textContent='已解除配对，可重新搜索选择设备';toast('配对已解除')});
for(const op of ['accept','reject'])$('#relay-'+op).onclick=()=>action(async()=>{await api('relay/pair',{action:op,target:snapshot.relay.pending});toast(op==='accept'?'已接受配对':'已拒绝配对')});
$('#relay-auto').onchange=()=>action(async()=>{const c={...snapshot.state.config,relay_auto_pair:$('#relay-auto').checked};await api('relay/auto-pair',{enabled:c.relay_auto_pair});toast(c.relay_auto_pair?'自动配对已开启，同组空闲主机会自动连接':'自动配对已关闭，已有配对保留')});

let relayTransferBusy=false;
setInterval(async()=>{
 if(relayTransferBusy||snapshot?.state.config.connection_mode!=='relay'||!snapshot.relay?.online)return;
 relayTransferBusy=true;
 try{const items=await api('relay/transfers');$('#relay-transfers').textContent=items.map(x=>`${x.artifact} · ${x.ready?'云端校验完成，等待主机接收':'上传 '+Math.round(x.uploaded/x.size*100)+'%'} · ${(x.uploaded/1048576).toFixed(1)} / ${(x.size/1048576).toFixed(1)} MB`).join('\n')||'暂无云端缓存片段'}catch(e){$('#relay-transfers').textContent='传输状态暂不可用'}finally{relayTransferBusy=false}
},2000);

$('#obs-start').onclick=()=>action(async()=>{const b=$('#obs-start');b.disabled=true;try{await api('obs/start',{});toast('正在启动无头 OBS，请查看启动状态')}finally{b.disabled=snapshot?.obs_launch?.phase==='starting'}});

function updateCustomHUDFields(){const m=$('#custom-hud-mode').value;for(const [id,show] of [['url',m==='url'],['source',m==='source'],['width',['builtin','url'].includes(m)],['height',['builtin','url'].includes(m)]]){$('#custom-hud-'+id+'-row').classList.toggle('hidden',!show);$('#custom-hud-'+id).disabled=!show}$('#custom-hud-url').required=m==='url';$('#custom-hud-source').required=m==='source'}
$('#hud-settings').onclick=()=>{const h=snapshot?.state.hud||{};$('#custom-hud-mode').value=h.mode||'builtin';$('#custom-hud-url').value=h.url||'';$('#custom-hud-source').value=h.source||'';$('#custom-hud-width').value=h.width||1920;$('#custom-hud-height').value=h.height||1080;$('#custom-hud-feedback').textContent='';updateCustomHUDFields();$('#custom-hud-dialog').showModal()};
$('#custom-hud-mode').onchange=updateCustomHUDFields;
$('#custom-hud-refresh').onclick=()=>action(async()=>{const r=await api('hud/inputs');const names=(r.inputs||[]).filter(x=>!['Project Replay Team HUD','Project Replay Custom HUD'].includes(x.inputName));$('#custom-hud-sources').innerHTML=names.map(x=>`<option value="${escapeHTML(x.inputName)}"></option>`).join('');$('#custom-hud-feedback').textContent='已读取 '+names.length+' 个 OBS 源，可在源名称输入框选择'});
$('#custom-hud-form').onsubmit=e=>{e.preventDefault();action(async()=>{const button=e.target.querySelector('[type=submit]');button.disabled=true;try{await api('hud/settings',{mode:$('#custom-hud-mode').value,url:$('#custom-hud-url').value.trim(),source:$('#custom-hud-source').value.trim(),width:Number($('#custom-hud-width').value),height:Number($('#custom-hud-height').value),keep_native:false});$('#custom-hud-feedback').textContent='设置已保存，正在应用到 OBS…';const r=await applyHUD();$('#custom-hud-feedback').textContent=r.warning||'HUD 已应用';$('#custom-hud-dialog').close()}catch(err){$('#custom-hud-feedback').textContent=err.message;throw err}finally{button.disabled=false}})};

$('#hud-zip-import').onclick=()=>action(async()=>{const file=$('#hud-zip-file').files[0];if(!file)throw Error('请选择本地 HUD ZIP 包');if(!file.name.toLowerCase().endsWith('.zip'))throw Error('请选择 .zip 文件');if(file.size>100*1024*1024)throw Error('ZIP 最大 100 MB');const b=$('#hud-zip-import');b.disabled=true;$('#hud-import-status').textContent='正在上传 '+file.name+'…';try{const r=await fetch('/api/hud/import?name='+encodeURIComponent(file.name),{method:'POST',headers:{'Content-Type':'application/zip'},body:file});const body=await r.json();if(!r.ok)throw Error(body.error||'HUD 上传失败');toast('ZIP 已上传，正在自动解压并启用到无头 OBS');$('#hud-zip-file').value=''}finally{b.disabled=false}});

fetch('/scoredeck/config').then(r=>r.json()).then(({origin})=>{if(!origin)return;const allowed=[origin,origin.replace('127.0.0.1','localhost')];window.addEventListener('message',e=>{if(e.source===parent&&allowed.includes(e.origin)&&e.data?.type==='scoredeck-open-settings')openSettings();});}).catch(()=>{});
