const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http');
const pack=require('../server/full-package.cjs'),{createDefaultState}=require('../server/default-state.cjs');
const put=(root,name,value)=>{const p=path.join(root,name);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,typeof value==='string'||Buffer.isBuffer(value)?value:JSON.stringify(value));};
test('complete package preserves settings and display assets, excludes replay/recording caches, retains transitions and operator settings; corruption rolls back',async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'full-package-')),data=path.join(root,'old'),target=path.join(root,'new'),external=path.join(root,'recordings'),asset=path.join(root,'outside.mp4');let cap;
 const remote=http.createServer((q,r)=>{r.writeHead(200,{'Content-Type':'image/png'});r.end(Buffer.from('REMOTE-IMAGE'));});await new Promise(r=>remote.listen(0,'127.0.0.1',r));
 try{
  const state=createDefaultState();state.halftime={durationSeconds:91,backgroundVideo:'/media/bg.webm'};state.teams[0].logoPrimary='http://127.0.0.1:'+remote.address().port+'/logo.png';
  put(data,'broadcast-state.json',state);put(data,'settings.json',{port:17890,countdownPort:17891});put(data,'media/bg.webm',Buffer.alloc(8*1024*1024,17));put(data,'media/unused.png','UNUSED-STILL-SAVED');
  put(data,'radarhud/display-settings.json',{layer:'high',fade:13});put(data,'radarhud/recorded.json',{rounds:[1,2,3]});
  put(data,'integrations/settings.json',{replay:{port:7788,autoStart:false},voicebridge:{port:8787,autoStart:false}});
  put(data,'integrations/voicebridge/.env','DASHSCOPE_API_KEY=test-key\nRUNTIME_DIR='+external+'\n');put(data,'integrations/voicebridge/desktop-settings.json',{path:external});put(data,'integrations/voicebridge/api-settings.json',{ASR_MODEL:'custom',DEEPSEEK_API_KEY:'test-second-key'});
  put(external,'session/audio.wav',Buffer.from('RECORDING'));put(external,'operator.json',{directorDelaySeconds:10,keepMuted:true});put(external,'current.json',{sessionId:'old-session',mode:'demo'});fs.writeFileSync(asset,'EXTERNAL-CLIP');
  put(data,'integrations/replay/state.json',{state:{config:{match:'test',relay_token:'test-token'},output:{transition1:'intro.webm',delay:8},team_hud:true,artifacts:[{path:asset}],jobs:[{id:'old'}],half_queue:['old'],queue:['old']},paths:{old:asset}});put(data,'integrations/replay/clips/clip.mp4','CLIP');put(data,'integrations/replay/media/cache.mp4','CACHE');put(data,'integrations/replay/media/intro.webm','TRANSITION');put(data,'integrations/replay/raw-recordings.json',[asset]);put(data,'integrations/replay.backup-123/media/old.mp4','OLD-CACHE');put(data,'backups/a.json',{source:path.join(data,'media/bg.webm')});
  cap=await pack.capture(data);const file=path.join(root,'all.sdpack');const manifest=await pack.writePackage(cap,file);
  assert.ok(manifest.files.some(f=>f.name==='media/unused.png'));assert.equal(manifest.files.some(f=>/session|clips|cache.mp4|raw-recordings|backup-123/.test(f.name)),false);assert.equal(manifest.cachePolicy,'exclude-replay-and-recordings');assert.ok(manifest.files.some(f=>f.name.endsWith('media/intro.webm')));
  await pack.readPackage(file,target+'.restore-pending',target);
  fs.writeFileSync(target+'.restore-pending.ready','1');pack.applyPending(target);
  assert.equal(fs.existsSync(path.join(target,'integrations/voicebridge/runtime/session/audio.wav')),false);assert.deepEqual(JSON.parse(fs.readFileSync(path.join(target,'integrations/voicebridge/runtime/operator.json'))),{directorDelaySeconds:10,keepMuted:true,archiveMode:'demo'});assert.equal(fs.existsSync(path.join(target,'integrations/voicebridge/runtime/current.json')),false);
  assert.equal(JSON.parse(fs.readFileSync(path.join(target,'integrations/voicebridge/desktop-settings.json'))).path,path.join(target,'integrations/voicebridge/runtime'));
  assert.match(fs.readFileSync(path.join(target,'integrations/voicebridge/.env'),'utf8'),/DASHSCOPE_API_KEY=test-key/);
  assert.equal(JSON.parse(fs.readFileSync(path.join(target,'integrations/voicebridge/api-settings.json'))).DEEPSEEK_API_KEY,'test-second-key');
  const replay=JSON.parse(fs.readFileSync(path.join(target,'integrations/replay/state.json')));assert.deepEqual(replay.state.artifacts,[]);assert.deepEqual(replay.state.jobs,[]);assert.deepEqual(replay.state.half_queue,[]);assert.deepEqual(replay.paths,{});assert.equal(replay.state.config.relay_token,'test-token');assert.equal(replay.state.output.delay,8);assert.equal(replay.state.team_hud,true);assert.equal(fs.readFileSync(path.join(target,'integrations/replay/media/intro.webm'),'utf8'),'TRANSITION');assert.equal(fs.readFileSync(asset,'utf8'),'EXTERNAL-CLIP');assert.equal(fs.readFileSync(path.join(external,'session/audio.wav'),'utf8'),'RECORDING');
  const restored=JSON.parse(fs.readFileSync(path.join(target,'broadcast-state.json')));assert.equal(restored.halftime.durationSeconds,91);assert.equal(fs.readFileSync(path.join(target,restored.teams[0].logoPrimary.slice(1)),'utf8'),'REMOTE-IMAGE');
  assert.equal(await pack.hash(path.join(data,'media/bg.webm')),await pack.hash(path.join(target,'media/bg.webm')));
  // Old full packages are accepted, but their caches and cache indexes are ignored.
  put(data,'integrations/voicebridge/runtime/sessions/old/audio.wav','OLD-RECORDING');put(data,'integrations/voicebridge/runtime/current.json',{sessionId:'old',mode:'demo'});put(data,'integrations/voicebridge/runtime/operator.json',{directorDelaySeconds:12});put(data,'imported/legacy.mp4','OLD-EXTERNAL-CACHE');
  const legacy=path.join(root,'legacy.sdpack');await pack.writePackage({stage:data,relocation:[{from:data,to:''}]},legacy);const legacyStage=path.join(root,'legacy-stage');await pack.readPackage(legacy,legacyStage,target);assert.equal(fs.existsSync(path.join(legacyStage,'integrations/replay/media/cache.mp4')),false);assert.equal(fs.existsSync(path.join(legacyStage,'integrations/voicebridge/runtime/sessions')),false);assert.equal(fs.existsSync(path.join(legacyStage,'imported/legacy.mp4')),false);assert.equal(JSON.parse(fs.readFileSync(path.join(legacyStage,'integrations/voicebridge/runtime/operator.json'))).directorDelaySeconds,12);
  // Internal custom recording directory must be excluded before copying too.
  const internal=path.join(data,'custom-recording-cache');put(internal,'sessions/a/track.wav','INTERNAL-CACHE');put(internal,'operator.json',{directorDelaySeconds:20});put(data,'integrations/voicebridge/desktop-settings.json',{path:internal,maxGB:10});const internalCapture=await pack.capture(data);try{assert.equal(fs.existsSync(path.join(internalCapture.stage,'custom-recording-cache')),false);assert.equal(fs.existsSync(path.join(internalCapture.stage,'imported/legacy.mp4')),false);assert.equal(JSON.parse(fs.readFileSync(path.join(internalCapture.stage,'integrations/voicebridge/runtime/operator.json'))).directorDelaySeconds,20);}finally{fs.rmSync(internalCapture.temp,{recursive:true,force:true});}
  const broken=path.join(root,'bad.sdpack');fs.copyFileSync(file,broken);const fd=fs.openSync(broken,'r+');fs.writeSync(fd,Buffer.from([255]),0,1,fs.statSync(broken).size-1);fs.closeSync(fd);
  await assert.rejects(pack.readPackage(broken,path.join(root,'bad-stage'),target),/校验失败/);assert.equal(fs.existsSync(path.join(root,'bad-stage')),false);
  // No arbitrary writes from archive paths, including Windows aliases.
  const magic=Buffer.from('SCOREDECK-FULL-PACK-1\n'),m=Buffer.from(JSON.stringify({format:'ScoreDeck-Full',version:1,relocation:[],files:[{name:'../escape',size:0,sha256:'0'.repeat(64)}]})),n=Buffer.alloc(4);n.writeUInt32LE(m.length);fs.writeFileSync(broken,Buffer.concat([magic,n,m]));await assert.rejects(pack.readPackage(broken,path.join(root,'bad-stage'),target),/清单无效/);
 }finally{remote.close();if(cap)fs.rmSync(cap.temp,{recursive:true,force:true});fs.rmSync(root,{recursive:true,force:true});}
});
