const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');const half=require('../server/halftime.cjs'),{createAutomation}=require('../server/halftime-auto.cjs');
test('GSI halftime automation: explicit phase, one shot, resume, manual override, disable and persisted dedupe',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sd-auto-'));let state={liveScene:'prematch',entrance:{status:'idle'},halftime:half.normalize()},packet={connected:true,sourceAgeMs:10,phase:'live',map:{name:'de_dust2',phase:'live',round:11,teamCT:{score:7},teamT:{score:4}}};let writes=0;const args={file:path.join(dir,'auto.json'),getState:()=>state,commit:s=>{state=s;writes++},readGSI:async()=>packet};let auto=createAutomation(args);
 try{
 await auto.tick();assert.equal(writes,0);packet.phase='timeout_ct';await auto.tick();assert.equal(writes,0);packet.phase='over';await auto.tick();assert.equal(writes,0);
 packet.phase='halftime';packet.map.phase='intermission';packet.map.round=12;packet.map.teamT.score=5;await auto.tick();assert.equal(writes,1);assert.equal(state.liveScene,'prematch');assert.equal(state.halftime.clock.status,'running');assert.equal(state.halftime.frozen.a,7);const deadline=state.halftime.clock.endAt;
 await auto.tick();assert.equal(writes,1);assert.equal(state.halftime.clock.endAt,deadline);
 auto.close();auto=createAutomation(args);await auto.tick();assert.equal(writes,1); // restarting does not restart the clock
 state.liveScene='postmatch';await auto.tick();assert.equal(auto.meta().active,true);assert.equal(state.liveScene,'postmatch');await auto.tick();assert.equal(state.liveScene,'postmatch');
 packet.phase='freezetime';packet.map.phase='live';await auto.tick();packet.phase='halftime';packet.map.phase='intermission';await auto.tick();assert.equal(state.liveScene,'postmatch'); // repeated phase does not retrigger
 packet.map.round=0;packet.map.phase='warmup';packet.phase='warmup';await auto.tick();packet.map.round=12;packet.map.phase='intermission';packet.phase='halftime';await auto.tick();assert.equal(state.liveScene,'postmatch');assert.equal(auto.meta().active,true);
 packet.map.phase='live';packet.phase='freezetime';await auto.tick();assert.equal(auto.meta().active,true);packet.phase='live';packet.phaseEndsIn=110;await auto.tick();assert.equal(state.liveScene,'postmatch');assert.equal(auto.meta().active,false);
 packet.phase='freezetime';await auto.show();await auto.tick();assert.equal(auto.meta().active,true); // explicit manual show does not immediately vanish on a live frame
 await auto.hide();assert.equal(state.liveScene,'postmatch');
 state.halftime.autoEnabled=false;packet.map.name='de_nuke';packet.map.phase='intermission';packet.phase='halftime';await auto.tick();assert.equal(state.liveScene,'postmatch');
 packet.sourceAgeMs=20000;state.halftime.autoEnabled=true;await auto.tick();assert.equal(state.liveScene,'postmatch');assert.equal(auto.meta().connected,false);
 }finally{auto.close();fs.rmSync(dir,{recursive:true,force:true});}
});
test('map victory triggers full highlights once on same output, includes overtime, new map hides it',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sd-full-'));let state={halftime:half.normalize(),highlightLayouts:{fullAuto:true},liveScene:'prematch'},g={connected:true,sourceAgeMs:0,phase:'over',map:{name:'de_anubis',phase:'live',round:29,teamCT:{score:16},teamT:{score:14}}};const a=createAutomation({file:path.join(dir,'auto.json'),getState:()=>state,commit:s=>state=s,readGSI:async()=>g});try{await a.tick();assert.equal(a.meta().active,false);g.map.phase='gameover';await a.tick();assert.equal(a.meta().mode,'full');assert.equal(a.meta().active,true);const start=state.halftime.media.startAt;await a.tick();assert.equal(state.halftime.media.startAt,start);await a.hide();await a.tick();assert.equal(a.meta().active,false);g.map.name='de_nuke';g.map.phase='warmup';await a.tick();g.map.phase='gameover';state.highlightLayouts.fullAuto=false;await a.tick();assert.equal(a.meta().active,false);state.highlightLayouts.fullAuto=true;state.halftime.autoEnabled=false;await a.tick();assert.equal(a.meta().active,true);assert.equal(state.liveScene,'prematch');g.map.name='de_mirage';g.map.phase='live';g.phase='freezetime';await a.tick();assert.equal(a.meta().active,false);}finally{a.close();fs.rmSync(dir,{recursive:true,force:true});}});
