const {test}=require('node:test'),assert=require('node:assert/strict');
const F=require('../server/tournament-flow.cjs'),D=require('../server/default-state.cjs');
const state=()=>D.createDefaultState(),fill=(s,st,start=0)=>st.slots.forEach((sl,i)=>sl.teamId=s.teams[start+i].id);
function finish(s,m,b=false){m.mapScores=[];m.mapDetails=[];m.scoreA=b?0:Math.floor(m.bestOf/2)+1;m.scoreB=b?Math.floor(m.bestOf/2)+1:0;m.status='completed';F.reconcile(s);}
function play(s,st,choose=()=>false){let n=0;while(true){F.reconcile(s);const m=F.matchesOf(s,st.id).find(m=>m.teamAId&&m.teamBId&&m.status!=='completed'&&!m.inactive);if(!m)break;finish(s,m,choose(m,n++));if(n>200)throw Error('did not converge');}return n;}
test('new tournaments are blank; no legacy event data is discarded during migration',()=>{const s=state();assert.equal(s.tournament.formatId,'flow');assert.deepEqual(s.stages,[]);assert.deepEqual(s.matches,[]);const old={...state(),tournament:{...state().tournament,formatId:'single-elim-8'},matches:[{id:'old',teamAId:'team-01',teamBId:'team-02',bestOf:1,scoreA:1,scoreB:0,status:'completed'}]};const migrated=D.migrateState(old);assert.equal(migrated.matches[0].status,'completed');F.blank(migrated);assert.equal(migrated.legacyFlowBackup.matches[0].id,'old');});
test('every single elimination size 2–32 produces n-1 played matches and exactly one champion',()=>{for(let n=2;n<=32;n++){let s=state(),st=F.addStage(s,'playoff',{teamCount:n});fill(s,st);assert.deepEqual(F.validate(s),[]);F.reconcile(s);const count=play(s,st,(m,i)=>i%3===0);assert.equal(count,n-1,`size ${n}`);const final=s.matches.find(m=>st.routes[F.win(m)]?.label==='冠军');assert.ok(F.result(final,'winner').id);assert.equal(s.matches.filter(m=>m.autoBye).length,2**Math.ceil(Math.log2(n))-n);assert.deepEqual(F.validate(D.migrateState(s)),[]);}});
test('waiting upstream entrants never become implicit byes',()=>{const s=state(),st=F.addStage(s,'playoff',{teamCount:3});st.slots[0].teamId=s.teams[0].id;F.reconcile(s);assert.equal(s.matches.filter(m=>m.autoBye).length,1);assert.notEqual(s.matches.at(-1).status,'completed');});
test('round robin fixtures are complete for odd/even sizes and double legs, BO2 draws count once',()=>{for(const n of [3,4,5,7,8])for(const format of ['round-robin','double-round']){const s=state(),st=F.addStage(s,'group',{groups:[{id:'g1',name:'A',size:n,format,bestOf:2,tieBreak:'round-diff'}]});fill(s,st);F.reconcile(s);assert.equal(s.matches.length,n*(n-1)/2*(format==='double-round'?2:1));const counts={};for(const m of s.matches){const key=[m.teamAId,m.teamBId].sort().join('/');counts[key]=(counts[key]||0)+1;m.scoreA=1;m.scoreB=1;m.status='completed';m.mapScores=[];}assert.ok(Object.values(counts).every(n=>n===(format==='double-round'?2:1)));F.reconcile(s);const rows=F.groupTable(s,st,st.groups[0]);assert.ok(rows.every(r=>r.points===(n-1)*(format==='double-round'?2:1)));}});
test('four-team GSL finishes with 2/0 and 2/1 qualifiers; eight-team double elimination gives each non-finalist two losses',()=>{for(const type of ['gsl','double8']){const s=state(),st=type==='gsl'?F.addStage(s,'group',{groups:[{id:'g1',name:'A',size:4,format:'gsl',bestOf:3}]}):F.addStage(s,'playoff',{format:'double8',teamCount:8});fill(s,st);const count=play(s,st);assert.equal(count,type==='gsl'?5:14);const losses={};for(const m of s.matches){const loser=F.result(m,'loser').id;losses[loser]=(losses[loser]||0)+1;}if(type==='gsl')assert.deepEqual(Object.values(losses).sort(),[1,2,2]);else assert.ok(Object.values(losses).filter(n=>n===2).length>=6);}});
test('multiple independent stages route rank and match outcomes into exact slots; upstream correction clears descendants',()=>{const s=state(),g=F.addStage(s,'group',{groups:[{id:'g1',name:'A',size:3,format:'round-robin',bestOf:1}]}),p=F.addStage(s,'playoff',{teamCount:2});fill(s,g);g.routes[F.rank('g1',1)]={kind:'slot',stageId:p.id,slotId:p.slots[0].id};g.routes[F.rank('g1',2)]={kind:'slot',stageId:p.id,slotId:p.slots[1].id};assert.deepEqual(F.validate(s),[]);F.reconcile(s);assert.equal(F.matchesOf(s,p.id)[0].status,'tbd');play(s,g);const final=F.matchesOf(s,p.id)[0];assert.ok(final.teamAId&&final.teamBId);finish(s,final);const original=F.matchesOf(s,g.id)[0];original.status='upcoming';F.reconcile(s);assert.equal(final.teamAId,'');assert.equal(final.status,'tbd');assert.ok(final.invalidatedResult);assert.equal(final.scoreA,0);assert.equal(final.mapDetails.length,0);});
test('route validation rejects occupied slots, duplicate claims, backwards flow and cycles',()=>{const s=state(),a=F.addStage(s,'playoff',{teamCount:4}),b=F.addStage(s,'playoff',{teamCount:2}),ma=F.matchesOf(s,a.id),mb=F.matchesOf(s,b.id);let x=structuredClone(s);x.stages[0].routes[F.win(ma.at(-1))]={kind:'slot',stageId:b.id,slotId:b.slots[0].id};x.stages[0].routes[F.lose(ma.at(-1))]={kind:'slot',stageId:b.id,slotId:b.slots[0].id};assert.match(F.validate(x).join(),/一个位置/);x=structuredClone(s);x.stages[1].routes[F.win(mb[0])]={kind:'slot',stageId:a.id,slotId:a.slots[0].id};assert.match(F.validate(x).join(),/后续/);x=structuredClone(s);x.matches[0].entryA=null;F.setRole(x,ma.at(-1).id,'normal');x.stages[0].routes[F.win(ma.at(-1))]={kind:'match',matchId:ma[0].id,side:'A'};assert.match(F.validate(x).join(),/循环/);x=structuredClone(s);x.stages[1].slots[0].teamId='team-01';x.stages[0].routes[F.win(ma.at(-1))]={kind:'slot',stageId:b.id,slotId:b.slots[0].id};assert.match(F.validate(x).join(),/直邀/);});
test('Swiss completes 33 matches without rematches; ranks route only once final standings resolve',()=>{for(let trial=0;trial<4;trial++){const s=state(),st=F.addStage(s,'swiss'),next=F.addStage(s,'playoff',{teamCount:8});fill(s,st);for(let n=1;n<=8;n++)st.routes[F.rank('swiss',n)]={kind:'slot',stageId:next.id,slotId:next.slots[n-1].id};const count=play(s,st,(m,i)=>((i*7+trial)%5)<2);assert.equal(count,33);const pairs=F.matchesOf(s,st.id).filter(m=>!m.inactive).map(m=>[m.teamAId,m.teamBId].sort().join());assert.equal(new Set(pairs).size,33);const rows=F.swissTable(s,st);assert.equal(rows.filter(r=>r.won===3).length,8);assert.equal(rows.filter(r=>r.lost===3).length,8);assert.ok(next.slots.every(sl=>sl.resolvedTeamId));const first=F.matchesOf(s,st.id)[0];finish(s,first,first.scoreA>first.scoreB);assert.ok(F.matchesOf(s,st.id).some(m=>m.swissRound===2&&m.status!=='completed'));assert.ok(next.slots.every(sl=>!sl.resolvedTeamId));}});
test('custom matches accept BO1/3/5 and route into subsequent stages; data and rule copies round trip',()=>{const s=state(),a=F.addStage(s,'custom'),b=F.addStage(s,'playoff',{teamCount:2});fill(s,a);b.slots[1].teamId='team-03';const m=s.matches[0];a.routes[F.win(m)]={kind:'slot',stageId:b.id,slotId:b.slots[0].id};play(s,a);const copy=D.migrateState(JSON.parse(JSON.stringify(s)));assert.equal(copy.stages[1].slots[0].resolvedTeamId,m.teamAId);assert.deepEqual(copy.stages,s.stages);const fs=require('fs');assert.equal(fs.readFileSync(require('path').join(__dirname,'../server/tournament-flow.cjs'),'utf8'),fs.readFileSync(require('path').join(__dirname,'../dist/assets/tournament-flow.js'),'utf8'));});
