(function(root,factory){const api=factory(typeof module==='object'?require('./tournament-flow.cjs'):root.ScoreDeckFlow);if(typeof module==='object')module.exports=api;else root.ScoreDeckDisplay=api;})(globalThis,function(F){
'use strict';
const chunks=(xs,n)=>Array.from({length:Math.ceil(xs.length/n)},(_,i)=>xs.slice(i*n,i*n+n));
// Unknown or incomplete start times retain their original order after dated matches.
function startTime(m){if(!/^\d{4}-\d{2}-\d{2}$/.test(m.date||'')||!/^\d{2}:\d{2}$/.test(m.time||''))return null;const value=Date.parse(`${m.date}T${m.time}:00Z`);return Number.isFinite(value)?value:null;}
function chronological(ms){return ms.map((m,i)=>({m,i,time:startTime(m)})).sort((a,b)=>a.time===null?(b.time===null?a.i-b.i:1):b.time===null?-1:a.time-b.time||a.i-b.i).map(x=>x.m);}
function searchMatch(s,m,query){const words=String(query||'').trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);if(!words.length)return true;const teams=s.teams.filter(t=>[m.teamAId,m.teamBId].includes(t.id));const players=[...teams.flatMap(t=>t.players||[]),...(m.mapDetails||[]).flatMap(d=>[...(d.teamA||[]),...(d.teamB||[])])];const haystack=[...teams.flatMap(t=>[t.name,t.shortName]),...players.flatMap(p=>[p.id,p.name,p.nickname,p.playerId,p.steamId])].filter(Boolean).join(' ').toLocaleLowerCase();return words.every(w=>haystack.includes(w));}
function stage(s,key=s.selectedStageId){return s.stages?.find(st=>st.id===key)||s.stages?.[0];}
function matches(s,st){return st?chronological(F.matchesOf(s,st.id).filter(m=>!m.inactive&&!m.autoBye).sort((a,b)=>a.scheduleOrder-b.scheduleOrder)):[];}
function config(s,st=stage(s)){const raw={...s.flowDisplay?.[st?.id],...s.flowViewOverride};return {groupCount:[1,2,4].includes(Number(raw.groupCount))?Number(raw.groupCount):2,focusSize:[1,2,4].includes(Number(raw.focusSize))?Number(raw.focusSize):4,groupIds:Array.isArray(raw.groupIds)?raw.groupIds.filter(id=>st?.groups.some(g=>g.id===id)):[],matchIds:Array.isArray(raw.matchIds)?raw.matchIds.filter(id=>matches(s,st).some(m=>m.id===id)):[],focusMode:raw.focusMode==='manual'?'manual':'round',round:raw.round||'',schedule:raw.schedule||'pending'};}
function primary(s,key=s.selectedStageId,preferred=s.selectedMatchId){const st=stage(s,key),ms=matches(s,st);return ms.find(m=>m.id===preferred)||ms.find(m=>m.id===s.flowDisplay?.[st?.id]?.primaryMatchId)||ms.find(m=>m.status==='live')||ms.find(m=>m.status==='upcoming')||ms[0];}
function selectStage(s,key){const old=stage(s),m=primary(s);if(old&&m){s.flowDisplay||={};s.flowDisplay[old.id]={...s.flowDisplay[old.id],primaryMatchId:m.id};}s.selectedStageId=key;s.selectedMatchId=primary(s,key,'')?.id||'';s.flowOutputPage=0;return s;}
function focusMatches(s,st,c=config(s,st)){const ms=matches(s,st);if(c.focusMode==='manual')return c.matchIds.map(id=>ms.find(m=>m.id===id)).filter(Boolean);if(c.round==='@medals')return ms.filter(m=>['final','thirdPlace'].includes(m.role));if(c.round)return ms.filter(m=>m.round===c.round);return [...ms].sort((a,b)=>({live:0,upcoming:1,tbd:2,completed:3}[a.status]??2)-({live:0,upcoming:1,tbd:2,completed:3}[b.status]??2)||a.scheduleOrder-b.scheduleOrder);}
function ledger(s,st,groupId){const ms=matches(s,st).filter(m=>!groupId||m.groupId===groupId),ids=new Set(st.slots.filter(sl=>!groupId||sl.groupId===groupId).map(sl=>sl.resolvedTeamId||sl.teamId).filter(Boolean));ms.forEach(m=>{if(m.teamAId)ids.add(m.teamAId);if(m.teamBId)ids.add(m.teamBId);});const order=['冠军','亚军','季军','殿军','Qualified','进行中','待赛','淘汰'];return [...ids].map(id=>{const team=s.teams.find(t=>t.id===id);let won=0,lost=0;for(const m of ms){if(F.result(m,'winner').id===id)won++;if(F.result(m,'loser').id===id)lost++;}const outcomes=(s.flowOutcomes||[]).filter(o=>o.stageId===st.id&&o.teamId===id&&(!groupId||ms.some(m=>m.id===o.matchId)));return {team,won,lost,status:outcomes.at(-1)?.status||(won+lost?'进行中':'待赛')};}).filter(r=>r.team).sort((a,b)=>order.indexOf(a.status)-order.indexOf(b.status)||b.won-a.won||a.lost-b.lost);}
function bracketPages(s,st){const ms=matches(s,st),deps=F.dependencies(s),depths=new Map(),byId=new Map(ms.map(m=>[m.id,m]));function depth(m){if(depths.has(m.id))return depths.get(m.id);depths.set(m.id,0);const ancestors=(deps.get(m.id)||[]).map(id=>byId.get(id)).filter(Boolean);let value=ancestors.length?1+Math.max(...ancestors.map(depth)):0;if(m.swissRound&&!m.custom)value=m.swissRound-1;depths.set(m.id,value);return value;}const columns=[];for(const m of ms){let d=depth(m);if(F.isRoundRobin(st,m))d=st.groups.findIndex(g=>g.id===m.groupId);(columns[d]||=([])).push(m);}const pages=[];for(let start=0;start<columns.length;start+=4){const cols=Array.from({length:4},(_,i)=>columns[start+i]||[]);for(let row=0;row<Math.max(...cols.map(c=>c.length));row+=4){const nodes=cols.flatMap((col,i)=>col.slice(row,row+4).map((m,j)=>({m,col:i,row:j})));if(nodes.length)pages.push({kind:'bracket',nodes,start,columns:Math.max(...nodes.map(n=>n.col))+1});}}return pages;}
function pages(s,scene){const st=stage(s);if(!st)return [];const c=config(s,st);if(scene==='bracket')return bracketPages(s,st);
 if(scene==='knockoutFocus'||scene==='focus'&&st.type!=='group')return chunks(focusMatches(s,st,c),c.focusSize).map(ms=>({kind:'focus',matches:ms,size:c.focusSize}));
 if(scene==='schedule')return chunks(matches(s,st).filter(m=>c.schedule==='all'||c.schedule==='completed'?c.schedule==='all'||m.status==='completed':m.status!=='completed'),8).map(ms=>({kind:'schedule',matches:ms}));
 if(scene==='thirdPlace'){if(st.type!=='group')return [];const rows=st.groups.filter(g=>g.format!=='gsl').map(g=>({...F.groupTable(s,st,g)[2],groupName:g.name,groupId:g.id})).filter(r=>r.team).sort((a,b)=>b.points-a.points||b.roundDiff-a.roundDiff||b.mapDiff-a.mapDiff||a.team.name.localeCompare(b.team.name));return chunks(rows,12).map(rows=>({kind:'third',rows}));}
 if(st.type==='group'){const gs=st.groups.filter(g=>!c.groupIds.length||c.groupIds.includes(g.id)),rowLimit=c.groupCount===4?5:c.groupCount===2?10:12,parts=gs.flatMap(g=>{const rows=g.format==='gsl'?ledger(s,st,g.id):F.groupTable(s,st,g);return (chunks(rows,rowLimit).length?chunks(rows,rowLimit):[[]]).map((rows,i)=>({g,rows,start:i*rowLimit,total:g.size,record:g.format==='gsl'}));});return chunks(parts,c.groupCount).map(tables=>({kind:'tables',tables,count:c.groupCount,focus:scene==='focus'}));}
 if(st.type==='swiss')return [{kind:'swiss',rows:F.swissTable(s,st)}];
 return chunks(ledger(s,st),12).map(rows=>({kind:'record',rows}));
}
function page(s,scene){const all=pages(s,scene),index=all.length?Math.max(0,Math.floor(Number(s.flowOutputPage)||0))%all.length:0;return {st:stage(s),content:all[index],index,total:all.length};}
function sourceLabel(s,m,side){const st=F.stageOf(s,m.stageId),src=F.indexes(s).ins.get(`${m.id}/${side}`)||m[`entry${side}`];return F.label(s,st,src);}
return {stage,matches,config,primary,selectStage,focusMatches,ledger,bracketPages,pages,page,sourceLabel,startTime,chronological,searchMatch};
});
