const SCENES=['focus','standings','thirdPlace','prematch','bracket','knockoutFocus','postmatch','schedule','entrance','countdown','mapStats','mapBP'];
const TYPES=['replay','radar','scoredeck','image','video','web','none'];
const text=(v,f='',n=120)=>typeof v==='string'?v.slice(0,n):f;
const num=(v,f,min,max)=>Number.isFinite(Number(v))?Math.min(max,Math.max(min,Number(v))):f;
const color=(v,f)=>/^#[0-9a-f]{6}$/i.test(v||'')?v:f;
function source(v='') {v=text(v,'',2048).trim();if(!v)return '';if(/^\/media\/[a-zA-Z0-9_.-]+$/.test(v))return v;try{const u=new URL(v);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)throw 0;return u.href;}catch{throw Error('素材或网页地址须使用 HTTP(S)，或导入本地素材');}}
function slot(v={},type='none') {return {type:TYPES.includes(v.type)?v.type:type,scene:SCENES.includes(v.scene)?v.scene:'prematch',source:source(v.source),label:type==='replay'?'':text(v.label,'',40),showLabel:type==='replay'?false:v.showLabel===true,fit:['cover','contain','fill'].includes(v.fit)?v.fit:'contain',muted:typeof v.muted==='boolean'?v.muted:type!=='replay',loop:v.loop!==false,half:Number(v.half)===2?2:1,layer:['all','low','high'].includes(v.layer)?v.layer:'all',fade:num(v.fade,3,0,60),showPlayers:v.showPlayers!==false,speed:num(v.speed,1,.25,4)};}
function clock(v={},duration=60) {return {status:['idle','running','paused'].includes(v.status)?v.status:'idle',remainingMs:num(v.remainingMs,duration*1000,0,86400000),endAt:Number.isFinite(v.endAt)?v.endAt:null,offsetMs:num(v.offsetMs,0,0,1e12),startAt:Number.isFinite(v.startAt)?v.startAt:null};}
function normalize(v={}) {if(v.visualRevision!==1){v={...v};const old={'#030b29':'#181818','#f5ff00':'#ececec','#1436ff':'#333333'};for(const k of ['background','accent','blue'])if(old[v[k]])v[k]=old[v[k]];}return {visualRevision:1,autoEnabled:v.autoEnabled!==false,autoReturn:v.autoReturn!==false,autoScore:v.autoScore!==false,revision:num(v.revision,0,0,1e12),title:text(v.title,'中场休息',40),round:text(v.round,'小组赛 · 第一轮',70),roundAuto:v.roundAuto!==false,matchId:text(v.matchId),mapIndex:Math.floor(num(v.mapIndex,0,0,4)),durationSeconds:Math.round(num(v.durationSeconds,60,1,86400)),endText:text(v.endText,'即将继续',30),showEndText:v.showEndText!==false,showRound:v.showRound!==false,showTitle:v.showTitle!==false,showTimer:v.showTimer!==false,showScore:v.showScore!==false,showMap:v.showMap!==false,showLogos:v.showLogos!==false,scoreSource:['manual','match','gsi'].includes(v.scoreSource)?v.scoreSource:'manual',gsiLeft:v.gsiLeft==='T'?'T':'CT',teamAId:text(v.teamAId),teamBId:text(v.teamBId),nameA:text(v.nameA,'',60),nameB:text(v.nameB,'',60),logoA:source(v.logoA),logoB:source(v.logoB),scoreA:Math.floor(num(v.scoreA,0,0,999)),scoreB:Math.floor(num(v.scoreB,0,0,999)),mapName:text(v.mapName,'',60),frozen:v.frozen&&typeof v.frozen==='object'?{a:Math.floor(num(v.frozen.a,0,0,999)),b:Math.floor(num(v.frozen.b,0,0,999)),map:text(v.frozen.map,'',60),at:num(v.frozen.at,0,0,1e15)}:null,background:color(v.background,'#181818'),accent:color(v.accent,'#ececec'),blue:color(v.blue,'#333333'),foreground:color(v.foreground,'#ffffff'),backgroundImage:source(v.backgroundImage),backgroundVideo:source(v.backgroundVideo),backgroundFit:['cover','contain','fill'].includes(v.backgroundFit)?v.backgroundFit:'cover',decoration:v.decoration!==false,transparent:v.transparent===true,titleScale:num(v.titleScale,1,.4,1.4),timerScale:num(v.timerScale,1,.4,1.4),scoreScale:num(v.scoreScale,1,.5,1.4),roundScale:num(v.roundScale,1,.5,1.5),leftPercent:num(v.leftPercent,66,30,75),gap:num(v.gap,24,0,80),clock:clock(v.clock,num(v.durationSeconds,60,1,86400)),media:clock(v.media),left:slot(v.left,'replay'),right:slot(v.right,'radar')};}
const remaining=(c,now)=>c.status==='running'?Math.max(0,c.endAt-now):c.remainingMs;
const elapsed=(c,now)=>c.offsetMs+(c.status==='running'?Math.max(0,now-c.startAt):0);
function action(input,op,now=Date.now()) {const h=normalize(input);if(op==='start'){if(h.clock.status==='running'&&remaining(h.clock,now)>0)return h;const ms=h.clock.status==='paused'&&h.clock.remainingMs>0?h.clock.remainingMs:h.durationSeconds*1000;h.clock={...h.clock,status:'running',remainingMs:ms,endAt:now+ms};h.media={...h.media,status:'running',startAt:now};}else if(op==='pause'){h.clock={...h.clock,status:'paused',remainingMs:remaining(h.clock,now),endAt:null};h.media={...h.media,status:'paused',offsetMs:elapsed(h.media,now),startAt:null};}else if(op==='reset'){h.clock=clock({},h.durationSeconds);h.media=clock();}else if(op==='restart-media'){h.media={...clock(),status:'running',startAt:now};}else if(op==='pause-media'){h.media={...h.media,status:'paused',offsetMs:elapsed(h.media,now),startAt:null};}else if(op==='resume-media'){if(h.media.status!=='running')h.media={...h.media,status:'running',startAt:now};}else throw Error('未知中场操作');h.revision++;return h;}
function resolve(state,h){const match=state.matches.find(m=>m.id===(h.matchId||state.selectedMatchId));const a=state.teams.find(t=>t.id===(h.teamAId||match?.teamAId)),b=state.teams.find(t=>t.id===(h.teamBId||match?.teamBId));const map=match?.mapScores?.[h.mapIndex];const s=h.scoreSource==='match'?{a:map?.a??'—',b:map?.b??'—',map:map?.map||''}:h.scoreSource==='gsi'?(h.frozen||{a:'—',b:'—',map:''}):{a:h.scoreA,b:h.scoreB,map:map?.map||''};return {round:h.roundAuto?(match?.round||match?.stage||h.round):h.round,nameA:h.nameA||a?.name||'ALPHA',nameB:h.nameB||b?.name||'BETA',logoA:h.logoA||a?.logoPrimary||'',logoB:h.logoB||b?.logoPrimary||'',scoreA:s.a,scoreB:s.b,map:h.mapName||s.map||'DUST II'};}
module.exports={normalize,action,remaining,elapsed,resolve,SCENES,source};
