'use strict';
const half=require('./halftime.cjs'),M=require('./match-data.cjs');
const TYPES=['replay','radar','scoredeck','nameA','nameB','shortA','shortB','logoA','logoB','scoreA','scoreB','mapName','mapIcon','bp','title','round','timer','text','image','video'];
const num=(v,d,min,max)=>Number.isFinite(Number(v))?Math.min(max,Math.max(min,Number(v))):d;
function element(v,i){if(!TYPES.includes(v.type))throw Error('未知画面元素');return {id:String(v.id||'element'+i).replace(/[^a-zA-Z0-9_-]/g,'').slice(0,60)||'element'+i,type:v.type,x:num(v.x,0,0,1920),y:num(v.y,0,0,1080),w:num(v.w,320,20,1920),h:num(v.h,180,20,1080),fontSize:num(v.fontSize,48,10,250),color:/^#[0-9a-f]{6}$/i.test(v.color)?v.color:'#ffffff',text:String(v.text||'').slice(0,200),source:half.source(v.source),scene:half.SCENES.includes(v.scene)?v.scene:'schedule',fit:['contain','cover','fill'].includes(v.fit)?v.fit:'contain',muted:v.muted===true,loop:v.loop!==false,opacity:num(v.opacity,1,0,1),half:num(v.half,1,1,100),layer:['all','low','high'].includes(v.layer)?v.layer:'all',fade:num(v.fade,3,0,60),showPlayers:v.showPlayers!==false,speed:num(v.speed,1,.25,4)};}
const make=(type,x,y,w,h,extra={})=>({type,x,y,w,h,...extra});
function defaults(h,mode){const full=mode==='full';return {background:h.background,transparent:h.transparent,backgroundImage:h.backgroundImage,enabled:true,elements:[make('title',60,30,1050,90,{text:full?'全场精选':h.title,fontSize:62}),make('round',60,130,1100,45,{fontSize:28}),make('replay',60,205,1200,675),make('radar',1310,280,550,550),make('logoA',60,925,85,85),make('nameA',165,940,470,58),make('scoreA',655,925,100,90,{fontSize:72}),make('mapIcon',820,905,280,140),make('scoreB',1160,925,100,90,{fontSize:72}),make('nameB',1300,940,450,58),make('logoB',1775,925,85,85)].map((e,i)=>element({...e,id:mode+'-'+i},i))};}
function normalize(v={},h=half.normalize()){const r={revision:num(v.revision,0,0,1e12),fullAuto:v.fullAuto!==false};for(const mode of ['half','full']){const p=v[mode]||defaults(h,mode);if(!Array.isArray(p.elements)||p.elements.length>60)throw Error('每个画面最多 60 个元素');const els=p.elements.map(element);if(new Set(els.map(e=>e.id)).size!==els.length)throw Error('画面元素 ID 重复');r[mode]={enabled:p.enabled!==false,background:/^#[0-9a-f]{6}$/i.test(p.background)?p.background:'#14161b',transparent:!!p.transparent,backgroundImage:half.source(p.backgroundImage),elements:els};}return r;}
function resolve(s,h){const data=M.stats({...s,statsMapIndex:null}),m=M.currentMatch(s),a=data.teams[0]||{},b=data.teams[1]||{},old=half.resolve(s,h);return {...old,nameA:a.name||old.nameA,nameB:b.name||old.nameB,shortA:a.shortName||'',shortB:b.shortName||'',logoA:a.logoPrimary||'',logoB:b.logoPrimary||'',scoreA:data.score[0]??old.scoreA,scoreB:data.score[1]??old.scoreB,map:data.map||old.map,mapName:(data.map||old.map).replace(/^de_/,''),round:m?.round||old.round,bp:data.bp};}
module.exports={normalize,defaults,resolve,TYPES};
