function sdCustomId(){return globalThis.crypto?.randomUUID?.()||`element-${Date.now()}-${Math.random().toString(36).slice(2)}`;}
function sdCustomElement({element:e,preview=false}){
 const h=l.createElement,style={position:'absolute',left:e.x,top:e.y,width:e.width,height:e.height,transform:`rotate(${e.rotation}deg)`,opacity:e.opacity,borderRadius:e.radius,overflow:'hidden',background:e.transparent?'transparent':e.background,color:e.color,fontFamily:e.fontFamily,fontSize:e.fontSize,fontWeight:e.bold?700:400,textAlign:e.align,display:e.hidden?'none':'flex',alignItems:'center',justifyContent:{left:'flex-start',center:'center',right:'flex-end'}[e.align],whiteSpace:'pre-wrap',overflowWrap:'anywhere',lineHeight:1.25};
 return h('div',{className:'sd-custom-element','data-element-id':e.id,style},e.type==='text'?e.text:e.type==='shape'?null:e.src?h(e.type==='video'?'video':'img',{src:e.src,alt:e.name,style:{width:'100%',height:'100%',objectFit:e.fit},autoPlay:e.type==='video',playsInline:true,loop:e.loop,muted:preview||e.muted,onError:event=>{event.currentTarget.dataset.failed='true';}}):preview?h('span',{style:{fontSize:24,color:'#aaa'}},'请导入素材或填写地址'):null);
}
function sdCustomOutput({state,scene}){
 const h=l.createElement,p=ScoreDeckPanels.normalize(state.customPanels)[scene],[size,setSize]=l.useState(()=>({w:innerWidth,h:innerHeight}));
 l.useEffect(()=>{const resize=()=>setSize({w:innerWidth,h:innerHeight});addEventListener('resize',resize);return()=>removeEventListener('resize',resize);},[]);
 const scale=Math.min(size.w/1920,size.h/1080);
 return h('main',{className:'sd-custom-output','data-panel-id':scene,style:{background:p.transparent?'transparent':p.background}},h('div',{className:'sd-custom-canvas',style:{transform:`translate(-50%,-50%) scale(${scale})`,background:p.transparent?'transparent':p.background}},...p.elements.map(e=>h(sdCustomElement,{key:e.id,element:e,preview:new URLSearchParams(location.search).has('preview')}))));
}
function sdCustomEditor({state,commit,scene}){
 const h=l.createElement,p=ScoreDeckPanels.normalize(state.customPanels)[scene],ref=l.useRef(null),[scale,setScale]=l.useState(.4),[selected,setSelected]=l.useState(''),[error,setError]=l.useState(''),[busy,setBusy]=l.useState(false),[moving,setMoving]=l.useState(null),drag=l.useRef(null);
 const e=p.elements.find(x=>x.id===selected);
 l.useEffect(()=>{const observer=new ResizeObserver(([entry])=>setScale(entry.contentRect.width/1920));observer.observe(ref.current);return()=>observer.disconnect();},[]);
 const act=fn=>Promise.resolve(commit(s=>{s.customPanels=ScoreDeckPanels.normalize(s.customPanels);fn(s.customPanels[scene]);return s;})).then(()=>setError('')).catch(err=>setError(err.message));
 const patch=(id,values)=>act(panel=>{const item=panel.elements.find(x=>x.id===id);if(item)Object.assign(item,values);});
 const add=(type,src='',name='')=>{if(p.elements.length>=100){setError('每个面板最多 100 个元素');return;}const id=sdCustomId();setSelected(id);return act(panel=>panel.elements.push(ScoreDeckPanels.element({id,type,src,name:name||({text:'文字',image:'图片',video:'视频',shape:'色块'}[type]),width:type==='text'?800:640,height:type==='text'?180:360,transparent:type!=='shape'})));};
 const upload=async file=>{if(!file)return;const types=['image/png','image/jpeg','image/webp','video/mp4','video/webm'];if(!types.includes(file.type)){setError('请选择 PNG、JPG、WebP 图片或 MP4、WebM 视频');return;}if(file.size>(file.type.startsWith('video/')?256:8)*1024*1024){setError('图片最大 8 MB，视频最大 256 MB');return;}setBusy(true);try{const result=await SDClient.request('/api/media/custom-panel',{method:'POST',headers:{'Content-Type':file.type},body:file});await add(file.type.startsWith('video/')?'video':'image',result.url,file.name);}catch(err){setError(err.message);}finally{setBusy(false);}};
 const start=(event,item,resize=false)=>{if(event.button!==0)return;event.preventDefault();setSelected(item.id);event.currentTarget.setPointerCapture(event.pointerId);drag.current={id:item.id,x:event.clientX,y:event.clientY,item,resize,scale};setMoving({...item});};
 const move=event=>{const d=drag.current;if(!d)return;const dx=(event.clientX-d.x)/d.scale,dy=(event.clientY-d.y)/d.scale;setMoving({...d.item,...(d.resize?{width:Math.max(20,Math.round(d.item.width+dx)),height:Math.max(20,Math.round(d.item.height+dy))}:{x:Math.round(d.item.x+dx),y:Math.round(d.item.y+dy)})});};
 const end=()=>{const d=drag.current;if(d&&moving)patch(d.id,d.resize?{width:moving.width,height:moving.height}:{x:moving.x,y:moving.y});drag.current=null;setMoving(null);};
 const field=(label,key,type='text',props={})=>h(sdFlowInput,{key:e.id+key,label,value:e[key],type,...props,onChange:v=>patch(e.id,{[key]:type==='number'?Number(v):v})});
 const select=(label,key,options)=>h(sdFlowSelect,{label,value:String(e[key]),options,onChange:v=>patch(e.id,{[key]:v})});
 const check=(label,key)=>h('label',{className:'sd-custom-check'},h('input',{type:'checkbox',checked:e[key],onChange:event=>patch(e.id,{[key]:event.target.checked})}),label);
 const reorder=delta=>act(panel=>{const i=panel.elements.findIndex(x=>x.id===e.id),j=i+delta;if(i>=0&&j>=0&&j<panel.elements.length)[panel.elements[i],panel.elements[j]]=[panel.elements[j],panel.elements[i]];});
 return h('section',{className:'panel sd-custom-editor'},h('h2',null,`${p.name} · 画布编辑`),h('p',{className:'hint'},'1920 × 1080 · 点击元素选择，拖动移动，右下角拖动缩放。图层从下向上叠加，修改自动保存。'),
 h('div',{className:'sf-actions'},h(sdFlowInput,{label:'面板名称',value:p.name,onChange:name=>act(panel=>{panel.name=name;})}),h(sdFlowInput,{label:'画布背景色',type:'color',value:p.background,onChange:background=>act(panel=>{panel.background=background;})}),h('label',{className:'sd-custom-check'},h('input',{type:'checkbox',checked:p.transparent,onChange:event=>act(panel=>{panel.transparent=event.target.checked;})}),'透明画布'),...['text','shape','image','video'].map(type=>h(sdFlowButton,{key:type,disabled:busy||p.elements.length>=100,onClick:()=>add(type)},`新增${{text:'文字',shape:'色块',image:'图片',video:'视频'}[type]}`)),h('label',{className:'button secondary'},busy?'正在导入…':'导入图片 / 视频',h('input',{type:'file','aria-label':'导入图片 / 视频',accept:'image/png,image/jpeg,image/webp,video/mp4,video/webm',disabled:busy||p.elements.length>=100,onChange:event=>{upload(event.target.files?.[0]);event.target.value='';}}))),
 error&&h('p',{role:'alert',className:'sf-error'},error),h('div',{className:'sd-custom-layout'},h('div',null,h('div',{className:'sd-custom-editor-preview',ref,style:{aspectRatio:'16 / 9'}},h('div',{className:'sd-custom-canvas',style:{transform:`scale(${scale})`,background:p.transparent?'transparent':p.background}},...p.elements.map(item=>{const shown=moving?.id===item.id?moving:item;return h(l.Fragment,{key:item.id},h(sdCustomElement,{element:shown,preview:true}),!item.hidden&&h('div',{className:'sd-custom-handle '+(selected===item.id?'selected':''),style:{left:shown.x,top:shown.y,width:shown.width,height:shown.height,transform:`rotate(${shown.rotation}deg)`},onPointerDown:event=>start(event,item),onPointerMove:move,onPointerUp:end,onPointerCancel:()=>{drag.current=null;setMoving(null);}},selected===item.id&&h('button',{'aria-label':'缩放元素',className:'sd-custom-resize',onPointerDown:event=>{event.stopPropagation();start(event,item,true);},onPointerMove:event=>{event.stopPropagation();move(event);},onPointerUp:event=>{event.stopPropagation();end();}})));}))),
 h('div',{className:'sd-custom-layers'},h('strong',null,'图层（上方优先显示）'),!p.elements.length&&h('p',null,'添加文字、色块或导入素材开始编辑。'),...p.elements.slice().reverse().map(item=>h('button',{key:item.id,className:'button '+(selected===item.id?'primary':'secondary'),onClick:()=>setSelected(item.id)},`${item.hidden?'隐藏 · ':''}${item.name}`)))),
 h('div',{className:'sd-custom-properties'},e?h(l.Fragment,null,h('h3',null,'元素属性'),field('元素名称','name'),h('div',{className:'sd-custom-fields'},field('X 坐标','x','number'),field('Y 坐标','y','number'),field('宽度','width','number',{min:20}),field('高度','height','number',{min:20}),field('旋转角度','rotation','number'),field('不透明度','opacity','number',{min:0,max:1,step:.05}),field('圆角','radius','number')),check('隐藏元素','hidden'),check('元素背景透明','transparent'),field('元素背景色','background','color'),
 e.type==='text'&&h(l.Fragment,null,h('label',{className:'sf-field'},'文字内容',h(sdTextField,{key:e.id,as:'textarea','aria-label':'文字内容',rows:4,value:e.text,onChange:event=>patch(e.id,{text:event.target.value})})),field('字号','fontSize','number',{min:8,max:500}),field('字体','fontFamily'),field('文字颜色','color','color'),select('文字对齐','align',[['left','左对齐'],['center','居中'],['right','右对齐']]),check('粗体','bold')),
 ['image','video'].includes(e.type)&&h(l.Fragment,null,h(sdFlowInput,{key:e.id+'src',label:'素材地址',value:e.src,placeholder:'https://… 或导入本地文件',onChange:src=>{if(src&&!ScoreDeckPanels.source(src)){setError('素材地址须为 HTTP / HTTPS 地址或本地素材路径');return;}patch(e.id,{src});}}),select('填充方式','fit',[['contain','完整显示'],['cover','铺满裁剪'],['fill','拉伸填满']]),e.type==='video'&&h(l.Fragment,null,check('循环播放','loop'),check('静音','muted'),h('small',null,'编辑与预览始终静音；正式输出按此设置播放。'))),
 h('div',{className:'sf-actions'},h(sdFlowButton,{disabled:p.elements.at(-1)?.id===e.id,onClick:()=>reorder(1)},'上移一层'),h(sdFlowButton,{disabled:p.elements[0]?.id===e.id,onClick:()=>reorder(-1)},'下移一层'),h(sdFlowButton,{disabled:p.elements.length>=100,onClick:()=>{const id=sdCustomId();act(panel=>panel.elements.push({...e,id,name:e.name+' 副本',x:e.x+24,y:e.y+24}));setSelected(id);}},'复制元素'),h(sdFlowButton,{onClick:()=>{act(panel=>{panel.elements=panel.elements.filter(x=>x.id!==e.id);});setSelected('');}},'删除元素'))):h('p',null,'选择画布上的元素或图层以编辑属性。'))));
}
