function sdFlowDisplayControls({state,commit,scene='focus'}){
 const h=l.createElement,D=ScoreDeckDisplay,F=ScoreDeckFlow,st=D.stage(state),c=D.config(state,st),info=D.page(state,scene),[err,setErr]=l.useState('');
 const act=fn=>{Promise.resolve(commit(s=>{fn(s);return s;})).catch(e=>setErr(e.message));};
 const patch=values=>act(s=>{s.flowDisplay||={};s.flowDisplay[st.id]={...s.flowDisplay[st.id],...values};s.flowOutputPage=0;});
 const toggle=(field,id,max)=>{const values=c[field].includes(id)?c[field].filter(x=>x!==id):[...c[field],id];if(max&&values.length>max){setErr(`最多选择 ${max} 项`);return;}setErr('');patch({[field]:values});};
 return h('div',{className:'sfd-controls'},h(sdFlowSelect,{label:'输出赛段',value:st?.id||'',options:[['','选择赛段'],...(state.stages||[]).map(st=>[st.id,st.name])],onChange:id=>act(s=>D.selectStage(s,id))}),st&&h(l.Fragment,null,
 h('div',{className:'sfd-page-controls'},h(sdFlowButton,{disabled:info.total<2,onClick:()=>act(s=>{s.flowOutputPage=(info.index-1+info.total)%info.total;})},'上一页'),h('span',null,`当前画面 ${info.total?info.index+1:0} / ${info.total} 页`),h(sdFlowButton,{disabled:info.total<2,onClick:()=>act(s=>{s.flowOutputPage=(info.index+1)%info.total;})},'下一页')),
 h(sdFlowInput,{label:'输出页码',type:'number',min:1,max:Math.max(info.total,1),value:info.index+1,onChange:v=>act(s=>{s.flowOutputPage=Math.max(0,Math.min(info.total-1,Number(v)-1));})}),
 st.type==='group'&&h('details',{open:['focus','standings'].includes(scene)},h('summary',null,'积分与小组聚焦'),h(sdFlowSelect,{label:'每页小组数',value:String(c.groupCount),options:[['1','单组'],['2','双组'],['4','四组']],onChange:v=>patch({groupCount:Number(v)})}),h('small',null,'不勾选时显示全部小组；人数较多时自动分页。'),h('div',{className:'sfd-checks'},...st.groups.map(g=>h('label',{key:g.id},h('input',{type:'checkbox',checked:c.groupIds.includes(g.id),onChange:()=>toggle('groupIds',g.id)}),g.name)))),
 h('details',{open:scene==='knockoutFocus'||scene==='focus'&&st.type!=='group'},h('summary',null,'对阵聚焦'),h(sdFlowSelect,{label:'每页对阵数',value:String(c.focusSize),options:[['1','单场'],['2','两场'],['4','四场']],onChange:v=>patch({focusSize:Number(v)})}),h(sdFlowSelect,{label:'聚焦方式',value:c.focusMode,options:[['round','按轮次 / 自动'],['manual','手动选择对阵']],onChange:focusMode=>patch({focusMode})}),c.focusMode==='round'?h(sdFlowSelect,{label:'聚焦轮次',value:c.round,options:[['','全部 · 进行中 / 待赛优先'],['@medals','决赛与季军赛'],...[...new Set(D.matches(state,st).map(m=>m.round))].map(r=>[r,r])],onChange:round=>patch({round})}):h('div',{className:'sfd-checks'},...D.matches(state,st).map(m=>h('label',{key:m.id},h('input',{type:'checkbox',checked:c.matchIds.includes(m.id),onChange:()=>toggle('matchIds',m.id)}),`${m.round} · ${F.shortId(m)}`)))),
 h(sdFlowSelect,{label:'赛程列表范围',value:c.schedule,options:[['pending','未完成比赛'],['all','全部比赛'],['completed','已完成比赛']],onChange:schedule=>patch({schedule})}),h('small',null,'展示选择按赛段保存；积分、对阵与轮播均使用当前赛段。'),err&&h('p',{role:'alert'},err)));
}
function sdFlowLogo({team}){return l.createElement('span',{className:'sfd-logo',style:{'--team-color':team?.color||'#777'}},team?.logoPrimary?l.createElement('img',{src:team.logoPrimary,alt:''}):l.createElement('b',null,team?.shortName?.slice(0,4)||'TBD'));}
function sdFlowTeam({state,id,fallback='等待参赛队伍'}){const h=l.createElement,t=state.teams.find(t=>t.id===id);return h('span',{className:'sfd-team'},h(sdFlowLogo,{team:t}),h('span',null,h('b',{title:t?.name||fallback},t?.name||fallback),t&&h('small',null,t.shortName)));}
function sdFlowMatchCard({state,match:m,roster=true}){
 const h=l.createElement,D=ScoreDeckDisplay,F=ScoreDeckFlow,teams=['A','B'].map(side=>state.teams.find(t=>t.id===m[`team${side}Id`])),winner=F.result(m,'winner').id;
 return h('article',{className:'sfd-match-card '+(m.status==='live'?'is-live':''),'data-match-id':m.id},h('header',null,h('span',null,m.round),h('small',null,`${F.shortId(m)} · BO${m.bestOf}`)),h('div',{className:'sfd-status'},h('i',null),({live:'进行中',completed:'已结束',upcoming:'待赛',tbd:'等待晋级'}[m.status])),h('div',{className:'sfd-versus'},...['A','B'].map((side,i)=>h('div',{key:side,className:winner===m[`team${side}Id`]?'winner':''},h(sdFlowTeam,{state,id:m[`team${side}Id`],fallback:D.sourceLabel(state,m,side)}),h('strong',null,m.status==='upcoming'||m.status==='tbd'?'—':m[`score${side}`])))),
 roster&&h('div',{className:'sfd-lineups'},...teams.map((t,i)=>h('div',{key:i},h('small',null,t?.shortName||`选手阵容 ${i+1}`),...(t?t.players.filter((p,i)=>typeof p.starter==='boolean'?p.starter:i<5).slice(0,5):[]).map((p,j)=>h('div',{key:j,className:'sfd-player'},p.avatar?h('img',{src:p.avatar,alt:''}):h('span',null,String(j+1).padStart(2,'0')),h('span',null,h('b',null,p.id),h('small',null,p.role)))))),!teams[0]&&!teams[1]&&h('p',null,'参赛队伍确定后显示首发阵容')),
 h('footer',null,h('span',null,[m.date,m.time].filter(Boolean).join(' ')||'赛程待定'),h('b',null,m.role==='final'?'冠军争夺':m.role==='thirdPlace'?'季军争夺':'')));
}
function sdFlowTable({state,st,rows,kind='group',g,start=0,total,focus=false}){
 const h=l.createElement,F=ScoreDeckFlow,record=kind==='record',swiss=kind==='swiss',third=kind==='third',cols=record?['队伍','胜','负','状态']:swiss?['队伍','胜','负','BU','状态']:third?['队伍','小组','积分','净胜图','净胜小局']:['队伍','胜','平','负','积分','净胜图','净胜小局'];
 const status=(r,i)=>{if(record)return r.status;if(swiss)return r.won>=3?'已晋级':r.lost>=3?'已淘汰':'进行中';return '';};
 return h('section',{className:'sfd-table-panel'},h('header',null,h('h3',null,g?.name||(swiss?'瑞士轮排名':third?'跨组第三名':'赛段战绩')),h('small',null,total?`${start+1}—${Math.min(start+rows.length,total)} / ${total}`:record?'按终结状态与战绩展示':swiss?'3 胜晋级 · 3 负淘汰':'积分 · 净胜图 · 净胜小局')),h('table',null,h('thead',null,h('tr',null,h('th',null,'#'),...cols.map(x=>h('th',{key:x},x)),g&&g.format!=='gsl'&&h('th',null,'去向'))),h('tbody',null,...rows.map((r,i)=>{const to=g&&g.format!=='gsl'?st.routes[F.rank(g.id,start+i+1)]:null;return h('tr',{key:r.team.id},h('td',{className:'sfd-rank'},record?({'冠军':'1','亚军':'2','季军':'3','殿军':'4'}[r.status]||'—'):start+i+1),h('td',null,h(sdFlowTeam,{state,id:r.team.id})),...(record?[r.won,r.lost,status(r,i)]:swiss?[r.won,r.lost,r.bu,status(r,i)]:third?[r.groupName,r.points,r.mapDiff,r.roundDiff]:[r.won,r.drawn,r.lost,r.points,r.mapDiff,r.roundDiff]).map((v,n)=>h('td',{key:n,className:n===(record?2:swiss?3:-1)?'sfd-state-cell':''},v)),to&&h('td',{className:'sfd-route-cell',title:F.targetLabel(state,to)},to.kind==='slot'||to.kind==='match'?'↗ 晋级':to.kind==='eliminate'?'淘汰':to.label||'待配置'));}))),!rows.length&&h('p',{className:'sfd-empty-inline'},'等待参赛队伍'),focus&&g&&h('footer',null,...ScoreDeckDisplay.matches(state,st).filter(m=>m.groupId===g.id&&!m.custom&&m.status!=='completed').slice(0,1).map(m=>h('span',{key:m.id},`下一场 · ${m.round} · ${state.teams.find(t=>t.id===m.teamAId)?.shortName||'TBD'} vs ${state.teams.find(t=>t.id===m.teamBId)?.shortName||'TBD'}`))));
}
function sdFlowBroadcastBracket({state,content}){
 const h=l.createElement,F=ScoreDeckFlow,nodes=content.nodes,positions=new Map(nodes.map(n=>[n.m.id,n])),width=1784,height=640,cw=width/Math.max(2,content.columns),cardW=cw-34,edges=[];
 for(const n of nodes){const st=F.stageOf(state,n.m.stageId);for(const [key,to]of Object.entries(st.routes)){if((key===F.win(n.m)||key===F.lose(n.m))&&to.kind==='match'&&positions.has(to.matchId)){const b=positions.get(to.matchId),x=n.col*cw+cardW,y=n.row*156+(key.startsWith('win:')?110:130),tx=b.col*cw,ty=b.row*156+(to.side==='A'?58:88);edges.push(h('path',{key:key+to.matchId,d:`M${x} ${y} C${x+22} ${y} ${tx-22} ${ty} ${tx} ${ty}`,className:key.startsWith('lose:')?'loser':''}));}}}
 return h('div',{className:'sfd-bracket'},h('svg',{viewBox:`0 0 ${width} ${height}`,preserveAspectRatio:'none','aria-hidden':true},...edges),...nodes.map(n=>h('article',{key:n.m.id,'data-match-id':n.m.id,className:'sfd-bracket-node',style:{left:`${n.col*cw/width*100}%`,top:`${n.row*156/height*100}%`,width:`${cardW/width*100}%`}},h('header',null,h('b',null,n.m.round),h('small',null,`${F.shortId(n.m)} · BO${n.m.bestOf}`)),...['A','B'].map(side=>{const t=state.teams.find(t=>t.id===n.m[`team${side}Id`]);return h('div',{key:side,className:'sfd-bracket-team'},h(sdFlowLogo,{team:t}),h('span',{title:t?.name||ScoreDeckDisplay.sourceLabel(state,n.m,side)},t?.name||ScoreDeckDisplay.sourceLabel(state,n.m,side)),h('strong',null,['upcoming','tbd'].includes(n.m.status)?'—':n.m[`score${side}`]));}),h('footer',null,...['win','lose'].map(kind=>{const to=F.stageOf(state,n.m.stageId).routes[`${kind}:${n.m.id}`];return h('span',{key:kind,title:to?F.targetLabel(state,to):''},`${kind==='win'?'胜':'负'} → ${to?.kind==='match'?(state.matches.find(m=>m.id===to.matchId)?.round||'对阵')+' '+F.shortId(state.matches.find(m=>m.id===to.matchId))+' '+to.side:to?.kind==='slot'?'晋级 '+F.stageOf(state,to.stageId)?.name:to?.kind==='end'?to.label:to?.kind==='eliminate'?'淘汰':n.m.swissRound?'按战绩配对':F.isRoundRobin(F.stageOf(state,n.m.stageId),n.m)?'按积分排名':'待连接'}`);})))));
}
function sdFlowScene({state,scene}){
 const h=l.createElement,D=ScoreDeckDisplay,{st,content,index,total}=D.page(state,scene),titles={focus:st?.type==='group'?'赛段聚焦':'对阵聚焦',standings:st?.type==='playoff'||st?.type==='custom'?'赛段战绩':'积分与排名',thirdPlace:'跨组第三名',knockoutFocus:'对阵聚焦',bracket:'赛段赛程',schedule:'赛程与结果'};
 let body;if(!content)body=h('div',{className:'sfd-empty'},h('h3',null,scene==='thirdPlace'?'此赛段没有跨组第三名榜':'暂无可展示内容'),h('p',null,scene==='thirdPlace'?'请切换到含循环赛小组的赛段。':'请检查参赛队伍、比赛筛选或手动选择的对阵。'));
 else if(content.kind==='focus')body=h('div',{className:`sfd-focus-grid count-${content.matches.length}`},...content.matches.map(m=>h(sdFlowMatchCard,{key:m.id,state,match:m})));
 else if(content.kind==='bracket')body=h(sdFlowBroadcastBracket,{state,content});
 else if(content.kind==='tables')body=h('div',{className:`sfd-tables count-${content.count}`},...content.tables.map(t=>h(sdFlowTable,{key:t.g.id+'/'+t.start,state,st,rows:t.rows,kind:t.record?'record':'group',g:t.g,start:t.start,total:t.total,focus:content.focus})));
 else if(['swiss','record','third'].includes(content.kind))body=h('div',{className:'sfd-tables count-1 '+(content.kind==='swiss'?'sfd-swiss':'')},h(sdFlowTable,{state,st,rows:content.rows,kind:content.kind}));
 else body=h('div',{className:'sfd-schedule'},...content.matches.map(m=>h('article',{key:m.id,'data-match-id':m.id},h('div',null,h('b',null,m.round),h('small',null,`${ScoreDeckFlow.shortId(m)} · BO${m.bestOf}`)),h(sdFlowTeam,{state,id:m.teamAId,fallback:D.sourceLabel(state,m,'A')}),h('strong',null,['upcoming','tbd'].includes(m.status)?'VS':`${m.scoreA} : ${m.scoreB}`),h(sdFlowTeam,{state,id:m.teamBId,fallback:D.sourceLabel(state,m,'B')}),h('small',null,m.status==='completed'?'已结束':m.status==='live'?'进行中':[m.date,m.time].filter(Boolean).join(' ')||'待定'))));
 return h('section',{className:'scene sfd-output','data-stage-id':st?.id,'data-scene':scene},h('header',{className:'sfd-title'},h('div',null,h('small',null,[state.tournament.name,st?.name||'赛事流程'].filter(Boolean).join(' / ')),h('h2',null,titles[scene])),h('div',null,h('span',null,st?.type==='group'?'GROUP STAGE':st?.type==='swiss'?'SWISS STAGE':'CUSTOM STAGE'),h('b',null,`${total?index+1:0} / ${total}`))),body,h('footer',{className:'sfd-page-footer'},h('span',null,scene==='bracket'?'实线 · 胜者路线    虚线 · 败者路线    跨页对阵按编号衔接':scene==='standings'&&st?.type==='group'?'小组排名采用赛事设置中的同分规则':'队标、首发与赛果实时同步'),h('span',null,st?.name)));
}
function sdFlowCycleScope({state,node,onChange}){const h=l.createElement,D=ScoreDeckDisplay,st=D.stage(state,node.stageId||state.selectedStageId);return h('div',{className:'sf-cycle-scope'},h(sdFlowSelect,{label:'轮播赛段',value:node.stageId||'',options:[['','当前选中赛段'],...(state.stages||[]).map(st=>[st.id,st.name])],onChange:stageId=>onChange({stageId,flowMatchId:'',flowPage:0})}),h(sdFlowInput,{label:'轮播页码',type:'number',min:1,max:100,value:(node.flowPage||0)+1,onChange:value=>onChange({flowPage:Math.max(0,Number(value)-1)})}),['prematch','postmatch'].includes(node.scene)&&h(sdFlowSelect,{label:'轮播主对阵',value:node.flowMatchId||'',options:[['','该赛段的主对阵'],...D.matches(state,st).map(m=>[m.id,`${m.round} · ${ScoreDeckFlow.shortId(m)}`])],onChange:flowMatchId=>onChange({flowMatchId})}));}
function sdFlowPostScope({state,commit}){return l.createElement(sdFlowSelect,{label:'赛后赛段',value:ScoreDeckDisplay.stage(state)?.id||'',options:(state.stages||[]).map(st=>[st.id,st.name]),onChange:id=>commit(s=>ScoreDeckDisplay.selectStage(s,id))});}
