// Integrated into the existing React bundle; l is the shared React instance.
function sdFlowSelect({label,value,options,onChange,disabled=false}){return l.createElement('label',{className:'sf-field'},label,l.createElement('select',{'aria-label':label,value:value??'',disabled,onChange:e=>onChange(e.target.value)},options.map(([value,label])=>l.createElement('option',{key:value,value},label))));}
function sdFlowInput({label,value,onChange,type='text',...props}){return l.createElement('label',{className:'sf-field'},label,l.createElement(sdTextField,{'aria-label':label,type,value:value??'',onChange:e=>onChange(e.target.value),...props}));}
function sdFlowButton({children,onClick,disabled=false,primary=false,...props}){return l.createElement('button',{type:'button',className:'button '+(primary?'primary':'secondary'),onClick,disabled,...props},children);}
function sdFlowStagePicker({state,commit}){const h=l.createElement,F=ScoreDeckFlow;return h('div',{className:'sf-stage-picker'},h(sdFlowSelect,{label:'输出赛段',value:state.selectedStageId||state.stages?.[0]?.id||'',options:[['','选择赛段'],...(state.stages||[]).map(x=>[x.id,x.name])],onChange:value=>commit(s=>{s.selectedStageId=value;s.flowOutputPage=0;return s;})}),h(sdFlowInput,{label:'输出页码',type:'number',min:1,max:100,value:(state.flowOutputPage||0)+1,onChange:value=>commit(s=>{s.flowOutputPage=Math.max(0,Number(value)-1);return s;})}),h('small',null,'完整赛程显示所选赛段；积分与赛程列表按页展示。小组积分每页最多2组，未来赛程每页8场。'));}
function sdFlowEditor({state}){
 const h=l.createElement,F=ScoreDeckFlow,[selected,setSelected]=l.useState(()=>state.selectedStageId||state.stages?.[0]?.id||''),[tab,setTab]=l.useState('teams'),[error,setError]=l.useState(''),[link,setLink]=l.useState(null),[allGraph,setAllGraph]=l.useState(false),[notice,setNotice]=l.useState('');
 const stages=state.stages||[],stage=stages.find(x=>x.id===selected)||stages[0];
 const act=async(fn)=>{try{setError('');await SDClient.mutate(s=>{fn(s);F.assertValid(s);F.reconcile(s);F.refreshLifecycle(s);return s;});setNotice('设置已保存');}catch(e){setError(e.message)}};
 const incoming=F.enabled(state)?F.indexes(state):{ins:new Map(),slots:new Map()};
 const add=type=>act(s=>{const st=F.addStage(s,type);setSelected(st.id);setTab('teams');});
 const outputPort=(stageId,key)=>{setSelected(stageId);setTab('routes');setLink({stageId,key});};
 const targetPort=to=>{if(link){act(s=>F.setRoute(s,link.stageId,link.key,to));setLink(null);}};
 if(!F.enabled(state))return h('section',{className:'panel sf-editor'},h('h2',null,'赛事流程编辑器'),h('p',null,'当前存档使用旧版赛制。请建立自定义流程后配置并启用；队伍与素材会保留，原赛程将另存为备份。'),h(sdFlowButton,{primary:true,onClick:()=>{if(confirm('建立空白赛事流程？当前赛程会保存在内部快照中。'))act(s=>F.blank(s));}},'建立空白流程'));
 const notes=F.activationErrors(state),updateStage=patch=>act(s=>Object.assign(F.stageOf(s,stage.id),patch));
 return h('div',{className:'sf-editor'},
 h('section',{className:'panel sf-heading'},h('div',null,h('h2',null,'赛事流程'),h('p',null,'设置实时保存 · 每条晋级路径须通向终结状态，校验通过后方可启用。')),h('div',{className:'sf-actions'},...['group','swiss','playoff','custom'].map(type=>h(sdFlowButton,{key:type,primary:type==='group',onClick:()=>add(type)},'+ '+({group:'小组赛',swiss:'瑞士轮',playoff:'Playoff',custom:'单场对决'}[type]))))),
 h('section',{className:'panel sf-lifecycle'},h('div',null,h('b',null,F.isActive(state)?'● 已启用':'○ 草稿'),h('small',{role:'status'},(SDClient.pending?'正在保存…':notice)||('自动保存'+(state.lastSavedAt?' · '+new Date(state.lastSavedAt).toLocaleTimeString():''))),h('p',null,F.isActive(state)?'所有去向已校验，可录入赛果与投入播出。修改赛程结构将返回草稿。':`尚有 ${notes.length} 项配置待完成；草稿可随时继续编辑。`)),h('div',{className:'sf-actions'},h(sdFlowButton,{onClick:()=>act(s=>{s.flowSavedAt=new Date().toISOString();})},'保存设置'),h(sdFlowButton,{onClick:()=>{const issues=F.activationErrors(state);setError(issues.join('；'));setNotice(issues.length?'校验未通过':'校验通过：所有对阵路径均通向终结状态');}},'检查全部路径'),h(sdFlowButton,{primary:true,disabled:F.isActive(state),onClick:()=>act(s=>F.activate(s))},'校验并启用'))),
 error&&h('p',{className:'sf-error',role:'alert'},error),
 !stages.length?h('section',{className:'panel sf-empty'},h('span',null,'开始'),h('h3',null,'从一个赛段开始'),h('p',null,'这里没有预置赛程。使用上方按钮添加小组赛、瑞士轮或 Playoff。'),h('span',null,'结束')):
 h('div',{className:'sf-workspace'},
 h('aside',{className:'panel sf-rail'},h('small',null,'开始'),...stages.map((st,index)=>h('button',{key:st.id,className:'sf-stage '+(stage?.id===st.id?'active':''),onClick:()=>{setSelected(st.id);}},h('b',null,String(index+1).padStart(2,'0')),h('span',null,st.name,h('small',null,`${st.slots.length}个位置 · ${F.matchesOf(state,st.id).filter(m=>!m.autoBye).length}场`)))),h('small',null,'结束')),
 h('section',{className:'panel sf-details'},h('div',{className:'sf-actions'},h(sdFlowInput,{label:'赛段名称',value:stage.name,onChange:name=>updateStage({name})}),h(sdFlowButton,{disabled:stages.indexOf(stage)===0,onClick:()=>act(s=>{const i=s.stages.findIndex(x=>x.id===stage.id);[s.stages[i-1],s.stages[i]]=[s.stages[i],s.stages[i-1]];})},'上移'),h(sdFlowButton,{disabled:stages.indexOf(stage)===stages.length-1,onClick:()=>act(s=>{const i=s.stages.findIndex(x=>x.id===stage.id);[s.stages[i+1],s.stages[i]]=[s.stages[i],s.stages[i+1]];})},'下移'),h(sdFlowButton,{onClick:()=>{if(confirm('删除该赛段及其中比赛？关联去向将变为待连接。'))act(s=>F.removeStage(s,stage.id));}},'删除赛段')),
 h('div',{className:'sf-tabs'},...[['teams','参赛队伍'],['format','赛制配置'],['modules','对阵模块'],['routes','晋级去向']].map(([id,title])=>h('button',{key:id,className:tab===id?'active':'',onClick:()=>setTab(id)},title))),
 tab==='teams'&&h('div',{className:'sf-slot-grid'},...stage.slots.map(sl=>{const from=incoming.slots.get(`${stage.id}/${sl.id}`);return h('div',{key:sl.id,className:'sf-slot'},h(sdFlowSelect,{label:sl.label,value:sl.teamId,disabled:!!from,options:[['','等待晋级 / 待选'],...state.teams.map(t=>[t.id,t.name])],onChange:value=>act(s=>F.stageOf(s,stage.id).slots.find(x=>x.id===sl.id).teamId=value)}),from&&h('small',null,'← ',F.label(state,stage,from)),sl.resolvedTeamId&&h('strong',null,state.teams.find(t=>t.id===sl.resolvedTeamId)?.name),link&&h(sdFlowButton,{onClick:()=>targetPort({kind:'slot',stageId:stage.id,slotId:sl.id})},'连到此位置'));})),
 tab==='modules'&&h(sdFlowModules,{state,stage,act}),
 tab==='format'&&h(sdFlowConfig,{key:stage.id,stage,state,act}),
 tab==='routes'&&h('div',null,h('p',{className:'hint'},'循环赛按最终名次；淘汰赛按每场胜败。每个来源只能有一个去向，每个位置只能有一个来源。'),...F.outputs(state,stage).map(out=>h(sdFlowRoute,{key:out.key,state,stage,out,act,selected:link?.stageId===stage.id&&link?.key===out.key,onSelect:()=>outputPort(stage.id,out.key)})))
 )),
 stages.length>0&&h('section',{className:'panel sf-graph-panel'},h('div',{className:'sf-heading'},h('div',null,h('h3',null,'赛程图'),h('p',null,link?'已选来源。点击空白 A/B 位置或后续赛段的入场位置完成连线。':'点击比赛的「胜」「负」或小组名次，再点击目标位置连线；也可使用上方去向列表。')),h('div',{className:'sf-actions'},link&&h(sdFlowButton,{onClick:()=>setLink(null)},'取消连线'),h(sdFlowButton,{onClick:()=>setAllGraph(!allGraph)},allGraph?'仅看当前赛段':'查看完整流程'),...['normal','final','thirdPlace'].map(role=>h(sdFlowButton,{key:role,onClick:()=>{setTab('modules');act(s=>F.addMatch(s,stage.id,role));}},'+ '+({normal:'普通对阵',final:'决赛',thirdPlace:'季军赛'}[role]))))),h(sdFlowGraph,{state,stageId:allGraph?'':stage?.id,onSource:outputPort,onTarget:targetPort,link})),
 notes.length>0&&h('details',{className:'panel sf-notes'},h('summary',null,`${notes.length} 项配置未通过启用检查`),...notes.map((n,i)=>h('p',{key:i},n))));
}
function sdFlowConfig({stage,state,act}){
 const h=l.createElement,F=ScoreDeckFlow,[draft,setDraft]=l.useState(()=>({...structuredClone(stage),...structuredClone(stage.templateDraft||{})}));
 l.useEffect(()=>setDraft({...structuredClone(stage),...structuredClone(stage.templateDraft||{})}),[stage.id]);
 const fields=x=>({format:x.format,bestOf:x.bestOf,teamCount:x.teamCount,groups:structuredClone(x.groups)}),update=patch=>{const next={...draft,...patch};setDraft(next);act(s=>F.stageOf(s,stage.id).templateDraft=fields(next));},group=(i,patch)=>update({groups:draft.groups.map((g,n)=>n===i?{...g,...patch}:g)});
 const bo=[1,2,3,5].map(n=>[String(n),`BO${n}`]);
 return h('div',{className:'sf-config'},stage.type==='group'?h(l.Fragment,null,
 h(sdFlowInput,{label:'小组数量',type:'number',min:1,max:32,value:draft.groups.length,onChange:value=>{const n=Math.max(1,Math.min(32,Number(value)||1));update({groups:Array.from({length:n},(_,i)=>draft.groups[i]||{id:`g${i+1}`,name:`${i<26?String.fromCharCode(65+i):i+1}组`,size:4,format:'round-robin',bestOf:1,tieBreak:state.tournament.groupTieBreak})});}}),
 ...draft.groups.map((g,i)=>h('div',{className:'sf-config-group',key:g.id},h(sdFlowInput,{label:`第${i+1}组名称`,value:g.name,onChange:name=>group(i,{name})}),h(sdFlowInput,{label:`${g.name}队伍数量`,type:'number',min:2,max:32,disabled:g.format==='gsl',value:g.size,onChange:value=>group(i,{size:Number(value)})}),h(sdFlowSelect,{label:`${g.name}赛制`,value:g.format,options:[['round-robin','单循环'],['double-round','双循环'],['gsl','四队双败（GSL）']],onChange:format=>group(i,{format,...format==='gsl'?{size:4,bestOf:g.bestOf===2?3:g.bestOf}:{}})}),h(sdFlowSelect,{label:`${g.name}默认BO`,value:String(g.bestOf),options:g.format==='gsl'?bo.filter(x=>x[0]!=='2'):bo,onChange:v=>group(i,{bestOf:Number(v)})}),h(sdFlowSelect,{label:`${g.name}同分规则`,value:g.tieBreak,options:[['round-diff','净胜小局优先'],['head-to-head','胜负关系优先']],onChange:tieBreak=>group(i,{tieBreak})})))
 ):h('div',{className:'sf-config-group'},stage.type==='playoff'&&h(sdFlowSelect,{label:'淘汰赛模板',value:draft.format,options:[['single','单败淘汰（2—32队）'],['double8','8队双败（总决赛不重置）']],onChange:format=>update({format,...format==='double8'?{teamCount:8}:{}})}),h(sdFlowInput,{label:'入场队伍数',type:'number',min:2,max:32,disabled:stage.type==='swiss'||stage.type==='custom'||draft.format==='double8',value:draft.teamCount,onChange:value=>update({teamCount:Number(value)})}),h(sdFlowSelect,{label:'默认BO',value:String(draft.bestOf),options:bo.filter(x=>x[0]!=='2'),onChange:v=>update({bestOf:Number(v)})})),
 stage.type==='swiss'&&h('p',{className:'hint'},'16队瑞士轮：3胜晋级、3负淘汰、最多5轮，同战绩优先且避免重复交手。BU＝对手胜负差之和；完全同分按入场种子顺序。各轮比赛可单独调整 BO。'),
 draft.format==='double8'&&h('p',{className:'hint'},'总决赛为单场系列赛，不重置；可以额外添加比赛并修改去向。'),
 h('p',{className:'hint'},'模板参数会实时保存为草稿。应用模板会重建本赛段比赛和内部连线，清除本赛段赛果及手工去向。队伍位置与其他赛段保留；目标位置被删除时会要求先修正上游连线。'),
 h(sdFlowButton,{primary:true,onClick:()=>{if(F.matchesOf(state,stage.id).some(m=>m.status==='completed'||m.status==='live')&&!confirm('本赛段已有赛果，重建会清除赛果和本赛段去向，是否继续？'))return;act(s=>{Object.assign(F.stageOf(s,stage.id),fields(draft));delete F.stageOf(s,stage.id).templateDraft;F.regenerate(s,stage.id);});}},'应用模板并重建本赛段'));
}
function sdFlowModules({state,stage,act}){
 const h=l.createElement,F=ScoreDeckFlow,idx=F.indexes(state);
 return h('div',{className:'sf-modules'},...F.matchesOf(state,stage.id).map(m=>{const aggregate=F.isRoundRobin(stage,m)||stage.type==='swiss'&&!m.custom;return h('div',{key:m.id,className:'sf-module'},h('div',{className:'sf-actions'},h('b',null,F.shortId(m)),h(sdFlowInput,{label:`${F.shortId(m)} 轮次名称`,value:m.round,onChange:round=>act(s=>s.matches.find(x=>x.id===m.id).round=round)}),!aggregate&&h(sdFlowSelect,{label:`${F.shortId(m)} 对阵类型`,value:m.role||'normal',options:[['normal','普通对阵'],['final','决赛对阵'],['thirdPlace','季军赛对阵']],onChange:role=>act(s=>F.setRole(s,m.id,role))}),h(sdFlowSelect,{label:`${F.shortId(m)} BO`,value:String(m.bestOf),options:(F.isRoundRobin(stage,m)?[1,2,3,5]:[1,3,5]).map(n=>[String(n),`BO${n}`]),onChange:v=>act(s=>s.matches.find(x=>x.id===m.id).bestOf=Number(v))}),!aggregate&&h(sdFlowButton,{onClick:()=>{if(confirm('删除此对阵？指向它的连线将变为待连接。'))act(s=>F.removeMatch(s,m.id));}},'删除对阵')),
 !aggregate&&h('div',{className:'sf-actions'},...['A','B'].map(side=>h(sdFlowSelect,{key:side,label:`${F.shortId(m)} ${side}来源`,disabled:idx.ins.has(`${m.id}/${side}`),value:JSON.stringify(m[`entry${side}`]||null),options:[[JSON.stringify(null),idx.ins.has(`${m.id}/${side}`)?F.label(state,stage,idx.ins.get(`${m.id}/${side}`)):'等待连线'],...stage.slots.map(sl=>[JSON.stringify({kind:'slot',slotId:sl.id}),sl.label]),...state.teams.map(t=>[JSON.stringify({kind:'team',teamId:t.id}),t.name]),[JSON.stringify({kind:'bye'}),'明确轮空']],onChange:value=>act(s=>s.matches.find(x=>x.id===m.id)[`entry${side}`]=JSON.parse(value))}))),
 aggregate?h('small',null,'轮内对阵按赛制推进；通过最终排名出口设置终结去向。'):h('div',{className:'sf-module-exits'},...F.outputs(state,stage).filter(o=>o.matchId===m.id).map(out=>h(sdFlowRoute,{key:out.key,state,stage,out,act,onSelect:()=>{}}))));}));
}
function sdFlowRoute({state,stage,out,act,selected,onSelect}){
 const h=l.createElement,F=ScoreDeckFlow,to=stage.routes[out.key]||F.pending(),value=JSON.stringify(to),m=state.matches.find(m=>m.id===out.matchId),fixed=!!F.roleTerminals(m?.role),options=[[JSON.stringify(F.pending()),'待连接'],...F.TERMINALS.map(label=>[JSON.stringify(F.terminal(label)),`终结 · ${label}`])];
 for(const st of state.stages.slice(state.stages.indexOf(stage)+1))for(const sl of st.slots){const dst={kind:'slot',stageId:st.id,slotId:sl.id};options.push([JSON.stringify(dst),'晋级 → '+F.targetLabel(state,dst)]);}
 for(const st of state.stages.slice(state.stages.indexOf(stage)))for(const dst of F.matchesOf(state,st.id))if(!F.isRoundRobin(st,dst)&&(st.type!=='swiss'||dst.custom)&&dst.id!==out.matchId)for(const side of ['A','B'])options.push([JSON.stringify({kind:'match',matchId:dst.id,side}),`${st===stage?'对阵':'晋级'} → ${st.name} / ${dst.round} ${F.shortId(dst)} · ${side}位`]);
 if(!options.some(x=>x[0]===value))options.unshift([value,F.targetLabel(state,to)]);
 return h('div',{className:'sf-route '+(selected?'selected':'')},h('button',{className:'sf-source-button',disabled:fixed,onClick:onSelect,title:fixed?'名次自动固定':'在图上连线'},out.label),h('span',null,'→'),h(sdFlowSelect,{label:`${out.label}去向`,disabled:fixed,value,options,onChange:v=>act(s=>F.setRoute(s,stage.id,out.key,JSON.parse(v)))}),fixed&&h('small',null,'自动终结'));
}
function sdFlowGraph({state,stageId='',onSource,onTarget,link,output=false}){
 const h=l.createElement,F=ScoreDeckFlow,stages=(state.stages||[]).filter(st=>!stageId||st.id===stageId),idx=F.indexes(state),nodes=[],edges=[],bands=[],positions=new Map();let offset=35,width=output?560:900;
 const add=(key,x,y,w,height,data)=>{const n={key,x,y,w,height,...data};nodes.push(n);positions.set(key,n);return n;};
 for(const st of stages){
  const startY=offset,allMs=F.matchesOf(state,st.id).filter(m=>!m.inactive),deps=F.dependencies(state),depths=new Map();let ms=allMs;
  if(output&&st.type==='playoff'&&st.format==='single'&&st.teamCount>16){const half=(state.flowOutputPage||0)%2;ms=allMs.filter(m=>{const r=/^R(\d+)-(\d+)$/.exec(F.shortId(m));if(!r)return true;let size=2;while(size<st.teamCount)size*=2;const count=size/(2**Number(r[1]));return count===1||Math.floor(Number(r[2])/(count/2))===half;});}
  const depth=m=>{if(depths.has(m.id))return depths.get(m.id);depths.set(m.id,0);const ds=(deps.get(m.id)||[]).map(k=>ms.find(m=>m.id===k)).filter(Boolean);const n=ds.length?1+Math.max(...ds.map(depth)):0;depths.set(m.id,n);return n;};
  const groupNodes=st.type==='group'?st.groups.filter(g=>g.format!=='gsl'):[];
  // Compact entry column, matches in topological columns.
  let maxBottom=startY+65;
  (output?[]:st.slots).forEach((sl,i)=>{const n=add(`slot/${st.id}/${sl.id}`,20,startY+45+i*50,178,42,{type:'slot',st,sl});maxBottom=Math.max(maxBottom,n.y+n.height);});
  const rows=new Map();
  for(const g of groupNodes){const n=add(`group/${st.id}/${g.id}`,output?20:244,startY+45+(rows.get(0)||0),242,72+g.size*30,{type:'group',st,g});rows.set(0,(rows.get(0)||0)+n.height+25);maxBottom=Math.max(maxBottom,n.y+n.height);for(const sl of st.slots.filter(sl=>sl.groupId===g.id))edges.push({from:`slot/${st.id}/${sl.id}`,to:n.key});}
  for(const m of ms.filter(m=>!F.isRoundRobin(st,m))){const d=st.type==='swiss'&&!m.custom?m.swissRound-1:depth(m),row=rows.get(d)||0,n=add(`match/${m.id}`,(output?20:244)+d*280,startY+45+row,242,output?80:118,{type:'match',st,m});rows.set(d,row+(output?95:142));maxBottom=Math.max(maxBottom,n.y+n.height);width=Math.max(width,n.x+n.w+50);}
  if(st.type==='playoff'&&st.format==='single'){for(const m of ms){const n=positions.get(`match/${m.id}`),parents=(deps.get(m.id)||[]).map(k=>positions.get(`match/${k}`)).filter(Boolean);if(n&&parents.length&&!m.custom)n.y=parents.reduce((sum,p)=>sum+p.y+p.height/2,0)/parents.length-n.height/2;}}
  const columns=new Map();for(const n of nodes.filter(n=>n.st===st&&n.type==='match')){if(!columns.has(n.x))columns.set(n.x,[]);columns.get(n.x).push(n);}for(const column of columns.values()){let bottom=0;for(const n of column.sort((a,b)=>a.y-b.y)){n.y=Math.max(n.y,bottom);bottom=n.y+n.height+24;maxBottom=Math.max(maxBottom,n.y+n.height);}}
  bands.push({st,y:startY,height:maxBottom-startY+35});offset=maxBottom+90;
 }
 const origin=(st,key)=>{if(key.startsWith('rank:')){const[,gid,n]=key.split(':');if(gid==='swiss')return {key:`swiss/${st.id}`,port:0};return {key:`group/${st.id}/${gid}`,port:72+(Number(n)-1)*30};}return {key:`match/${key.slice(key.indexOf(':')+1)}`,port:output?(key.startsWith('win:')?43:66):(key.startsWith('win:')?86:106)};};
 for(const st of stages){
  if(st.type==='swiss'){
   const band=bands.find(b=>b.st===st),x=(output?20:244)+5*280,n=add(`swiss/${st.id}`,x,band.y+45,230,60+16*27,{type:'swiss',st});width=Math.max(width,x+280);
  }
  for(const m of F.matchesOf(state,st.id))if(positions.has(`match/${m.id}`))for(const side of ['A','B']){const src=m[`entry${side}`];if(src?.kind==='slot')edges.push({from:`slot/${st.id}/${src.slotId}`,to:`match/${m.id}`,toPort:side==='A'?43:66});}
  for(const[key,to]of Object.entries(st.routes)){
   const from=origin(st,key);if(to.kind==='match')edges.push({from:from.key,port:from.port,to:`match/${to.matchId}`,toPort:to.side==='A'?43:66,loser:key.startsWith('lose:')});
   if(to.kind==='slot')edges.push({from:from.key,port:from.port,to:`slot/${to.stageId}/${to.slotId}`,loser:key.startsWith('lose:')});
  }
 }
 const name=id=>state.teams.find(t=>t.id===id)?.shortName||state.teams.find(t=>t.id===id)?.name||'';
 const port=(x,y,text,callback,key)=>h('g',{key,role:callback?'button':undefined,tabIndex:callback?0:undefined,'aria-label':text,onClick:callback,onKeyDown:e=>{if(callback&&['Enter',' '].includes(e.key)){e.preventDefault();callback();}},className:callback?'sf-graph-port':''},h('circle',{cx:x,cy:y,r:5}),h('text',{x:x+10,y:y+4},text));
 const svg=h('svg',{viewBox:`0 0 ${width} ${Math.max(offset,220)}`,width:output?'100%':width,height:output?'100%':Math.max(offset,220),className:'sf-svg',role:'img','aria-label':'自动生成的赛事赛程图'},h('defs',null,h('marker',{id:output?'sf-arrow-output':'sf-arrow',markerWidth:7,markerHeight:7,refX:6,refY:3.5,orient:'auto'},h('path',{d:'M0 0 L7 3.5 L0 7',fill:'#999'}))),
 ...bands.map(b=>h('g',{key:b.st.id},h('rect',{x:5,y:b.y-12,width:width-10,height:b.height+20,rx:10,className:'sf-band'}),h('text',{x:20,y:b.y+15,className:'sf-graph-title'},b.st.name))),
 ...edges.map((e,i)=>{const a=positions.get(e.from),b=positions.get(e.to);if(!a||!b)return null;const x=a.x+a.w,y=a.y+(e.port||a.height/2),tx=b.x,ty=b.y+(e.toPort||b.height/2),mid=Math.max(x+20,(x+tx)/2);return h('path',{key:i,d:`M${x},${y} C${mid},${y} ${tx-25},${ty} ${tx},${ty}`,fill:'none',stroke:e.loser?'#b69b69':'#9aa9bc',strokeWidth:1.4,strokeDasharray:e.loser?'4 4':undefined,markerEnd:`url(#${output?'sf-arrow-output':'sf-arrow'})`});}),
 ...nodes.map(n=>h('g',{key:n.key,'data-node':n.key,transform:`translate(${n.x} ${n.y})`},h('rect',{width:n.w,height:n.height,rx:7,className:'sf-node'}),n.type==='slot'?h(l.Fragment,null,h('text',{x:12,y:16,className:'sf-small'},n.sl.label),h('text',{x:12,y:33},name(n.sl.resolvedTeamId||n.sl.teamId)||'等待入场'),link&&port(n.w-18,21,'',()=>onTarget?.({kind:'slot',stageId:n.st.id,slotId:n.sl.id}),'target')):
 n.type==='match'?h(l.Fragment,null,h('text',{x:10,y:19,className:'sf-small'},`${n.m.round} · ${F.shortId(n.m)} · BO${n.m.bestOf}`),...['A','B'].map((side,i)=>{const src=idx.ins.get(`${n.m.id}/${side}`)||n.m[`entry${side}`],text=name(n.m[`team${side}Id`])||(n.m.swissRound>1?'同战绩自动配对':F.label(state,n.st,src));return h('g',{key:side,onClick:link?()=>onTarget?.({kind:'match',matchId:n.m.id,side}):undefined,className:link?'sf-target':''},h('rect',{x:6,y:29+i*24,width:230,height:23,fill:'transparent'}),h('text',{x:10,y:46+i*24},`${side}  ${text.length>(output?16:21)?text.slice(0,output?15:20)+'…':text}`),h('text',{x:215,y:46+i*24,textAnchor:'end'},n.m.autoBye?'—':n.m[`score${side}`]));}),!output&&port(12,88,'胜',onSource&&!F.roleTerminals(n.m.role)&&(n.st.type!=='swiss'||n.m.custom)?()=>onSource(n.st.id,F.win(n.m)):null,'winner'),!output&&h('text',{x:65,y:92,className:'sf-small'},F.targetLabel(state,n.st.routes[F.win(n.m)]||{kind:'pending'}).slice(0,22)),!output&&port(12,107,'负',onSource&&!F.roleTerminals(n.m.role)&&(n.st.type!=='swiss'||n.m.custom)?()=>onSource(n.st.id,F.lose(n.m)):null,'loser'),!output&&h('text',{x:65,y:111,className:'sf-small'},F.targetLabel(state,n.st.routes[F.lose(n.m)]||{kind:'pending'}).slice(0,22))):
 n.type==='group'?h(l.Fragment,null,h('text',{x:12,y:23,className:'sf-graph-title'},`${n.g.name} · ${n.g.format==='double-round'?'双循环':'单循环'}`),h('text',{x:12,y:45,className:'sf-small'},`${n.g.size}队 · BO${n.g.bestOf}`),...Array.from({length:n.g.size},(_,i)=>port(14,70+i*30,`第${i+1}名  ${F.targetLabel(state,n.st.routes[F.rank(n.g.id,i+1)]||F.pending()).slice(0,22)}`,onSource?()=>onSource(n.st.id,F.rank(n.g.id,i+1)):null,String(i)))):
 h(l.Fragment,null,h('text',{x:12,y:24,className:'sf-graph-title'},'瑞士轮最终排名'),...Array.from({length:16},(_,i)=>port(12,50+i*27,`第${i+1}名 → ${F.targetLabel(state,n.st.routes[F.rank('swiss',i+1)]).slice(0,18)}`,onSource?()=>onSource(n.st.id,F.rank('swiss',i+1)):null,String(i)))))));
 return h('div',{className:output?'sf-graph-output':'sf-graph-scroll'},svg);
}
function sdFlowSchedule({state,commit}){
 const h=l.createElement,F=ScoreDeckFlow,[filter,setFilter]=l.useState(state.selectedStageId||state.stages?.[0]?.id||''),[edit,setEdit]=l.useState(null),[resultFilter,setResultFilter]=l.useState('all'),[error,setError]=l.useState('');
 const act=fn=>SDClient.mutate(s=>{fn(s);F.assertValid(s);F.reconcile(s);F.refreshLifecycle(s);return s;}).then(()=>setError('')).catch(e=>setError(e.message));
 const matches=state.matches.filter(m=>(!filter||m.stageId===filter)&&!m.inactive&&sdResultVisible(m,resultFilter)).sort((a,b)=>a.scheduleOrder-b.scheduleOrder),idx=F.indexes(state);
 const name=id=>state.teams.find(t=>t.id===id)?.name;
 return h('div',{className:'sf-editor'},h('section',{className:'panel sf-heading'},h('h2',null,'赛程与赛果'),h('div',{className:'sf-actions'},h(sdFlowSelect,{label:'筛选赛段',value:filter,options:[['','全部赛段'],...(state.stages||[]).map(st=>[st.id,st.name])],onChange:setFilter}),h(sdFlowSelect,{label:'完成状态',value:resultFilter,options:[['hide','隐藏已完成'],['all','显示已完成'],['completed','只显示已完成']],onChange:setResultFilter}),h(sdFlowButton,{disabled:!filter,onClick:()=>act(s=>F.addMatch(s,filter))},'+ 单场对决'))),error&&h('p',{role:'alert',className:'sf-error'},error),!F.isActive(state)&&h('p',{className:'sf-warning'},'当前赛事为草稿。请在赛事设置中完成去向配置并“校验并启用”，然后录入赛果。'),!matches.length&&h('section',{className:'panel sf-empty'},'尚无比赛。请在赛事设置中添加赛段。'),...matches.map(m=>{const st=F.stageOf(state,m.stageId);return h('section',{key:m.id,className:'panel sf-match-card'},h('div',{className:'sf-match-head'},h('strong',null,`${st.name} / ${m.round} · ${F.shortId(m)}`),h('span',null,m.autoBye?'自动轮空':({tbd:'等待队伍',upcoming:'待赛',live:'进行中',completed:'已完成'}[m.status])),h(sdFlowButton,{onClick:()=>act(s=>{s.selectedMatchId=m.id;s.selectedStageId=m.stageId;})},state.selectedMatchId===m.id?'当前主对阵':'设为主对阵')),h('div',{className:'sf-match-content'},h('div',null,...['A','B'].map(side=>h('div',{key:side,className:'sf-match-team'},h('b',null,name(m[`team${side}Id`])||F.label(state,st,idx.ins.get(`${m.id}/${side}`)||m[`entry${side}`])),h('strong',null,m.autoBye?'—':m[`score${side}`])))),h('div',{className:'sf-actions'},h(sdFlowSelect,{label:`${F.shortId(m)} BO`,value:String(m.bestOf),options:(F.isRoundRobin(st,m)?[1,2,3,5]:[1,3,5]).map(n=>[String(n),`BO${n}`]),onChange:v=>act(s=>{const x=s.matches.find(x=>x.id===m.id);x.bestOf=Number(v);})}),h(sdFlowButton,{primary:true,disabled:!F.isActive(state)||!m.teamAId||!m.teamBId||m.autoBye,onClick:()=>setEdit(m.id)},'录入比分 / 数据'))),
 (!F.isRoundRobin(st,m)&&(st.type!=='swiss'||m.custom))&&h('details',{className:'sf-entry-edit'},h('summary',null,'入场来源与连线位置'),h('div',{className:'sf-actions'},...['A','B'].map(side=>h(sdFlowSelect,{key:side,label:`${F.shortId(m)} ${side}入场`,disabled:idx.ins.has(`${m.id}/${side}`),value:JSON.stringify(m[`entry${side}`]||null),options:[[JSON.stringify(null),idx.ins.has(`${m.id}/${side}`)?F.label(state,st,idx.ins.get(`${m.id}/${side}`)):'等待连线'],...st.slots.map(sl=>[JSON.stringify({kind:'slot',slotId:sl.id}),sl.label]),...(m.custom?state.teams.map(t=>[JSON.stringify({kind:'team',teamId:t.id}),t.name]):[]),[JSON.stringify({kind:'bye'}),'明确轮空']],onChange:value=>act(s=>{s.matches.find(x=>x.id===m.id)[`entry${side}`]=JSON.parse(value);})})),h(sdFlowButton,{onClick:()=>{if(confirm('删除这场对阵及其去向？'))act(s=>F.removeMatch(s,m.id));}},'删除单场对决'))),
 h('div',{className:'sf-actions'},h(sdFlowSelect,{label:`${F.shortId(m)} 比赛状态`,value:m.status,disabled:!F.isActive(state)||m.autoBye||!m.teamAId||!m.teamBId,options:[['tbd','待定'],['upcoming','待赛'],['live','进行中'],['completed','已完成']],onChange:value=>act(s=>{const x=s.matches.find(x=>x.id===m.id);x.status=value;if(value==='completed'){ScoreDeckRules.normalizeMatch(x);if(x.status!=='completed')throw Error('比分未达到完赛条件，请先录入地图比分或正确的大比分');}})}),...['A','B'].map(side=>h(sdFlowInput,{key:side,label:`${F.shortId(m)} ${side}大比分`,value:m[`score${side}`],disabled:!F.isActive(state)||m.autoBye||!m.teamAId||!m.teamBId,onChange:value=>act(s=>{const x=s.matches.find(x=>x.id===m.id);if(x.mapScores.some(ScoreDeckRules.validMap))throw Error('已有地图比分，请在“录入比分 / 数据”中修改以保持统计一致');x[`score${side}`]=/^(W|F|WW|FF)$/i.test(value)?value.toUpperCase():Math.max(0,Number(value)||0);})}))),
 h(sdResultExports,{state,match:m}),h(sdMatchData,{state,match:m,commit}),
 m.resultWarning&&h('p',{className:'sf-warning'},m.resultWarning),
 h('div',{className:'sf-actions'},h(sdFlowInput,{label:`${F.shortId(m)} 日期`,type:'date',value:m.date||'',onChange:value=>act(s=>{s.matches.find(x=>x.id===m.id).date=value;})}),h(sdFlowInput,{label:`${F.shortId(m)} 时间`,type:'time',value:m.time||'',onChange:value=>act(s=>{s.matches.find(x=>x.id===m.id).time=value;})})),m.resultInvalidated&&h('small',{className:'sf-warning'},'参赛队伍或上游赛果已变化；原赛果已清除，请核对后重新录入。'));}),edit&&state.matches.some(m=>m.id===edit)&&h(Xt,{state,match:state.matches.find(m=>m.id===edit),commit:(fn)=>act(fn),onClose:()=>setEdit(null)}));
}
